//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("GrantModel", "FK_Grant_Daily_Grant_GrantType", "Grant_GrantType", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(GrantBusinessLayer.Grant_GrantType), "Grant_Daily", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GrantBusinessLayer.Grant_Daily), true)]
[assembly: EdmRelationshipAttribute("GrantModel", "FK_Grant_Activity_Grant_Category", "Grant_Category", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(GrantBusinessLayer.Grant_Category), "Grant_Activity", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GrantBusinessLayer.Grant_Activity), true)]
[assembly: EdmRelationshipAttribute("GrantModel", "FK_Grant_Activity_Grant_Daily", "Grant_Daily", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(GrantBusinessLayer.Grant_Daily), "Grant_Activity", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GrantBusinessLayer.Grant_Activity), true)]
[assembly: EdmRelationshipAttribute("GrantModel", "Daily_Person", "Grant_Daily", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GrantBusinessLayer.Grant_Daily), "Person", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(GrantBusinessLayer.Person), true)]
[assembly: EdmRelationshipAttribute("GrantModel", "Grant_vActivityApproverGrant_Daily", "Grant_vActivityApprover", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(GrantBusinessLayer.Grant_vActivityApprover), "Grant_Daily", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GrantBusinessLayer.Grant_Daily), true)]
[assembly: EdmRelationshipAttribute("GrantModel", "FK_User_User_Person_Person", "Person", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(GrantBusinessLayer.Person), "User_User", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(GrantBusinessLayer.User), true)]
[assembly: EdmRelationshipAttribute("GrantModel", "ShiftUser", "Shift", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(GrantBusinessLayer.Shift), "User", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GrantBusinessLayer.User), true)]

#endregion

namespace GrantBusinessLayer
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class GrantEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new GrantEntities object using the connection string found in the 'GrantEntities' section of the application configuration file.
        /// </summary>
        public GrantEntities() : base("name=GrantEntities", "GrantEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new GrantEntities object.
        /// </summary>
        public GrantEntities(string connectionString) : base(connectionString, "GrantEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new GrantEntities object.
        /// </summary>
        public GrantEntities(EntityConnection connection) : base(connection, "GrantEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Grant_Category> Grant_Category
        {
            get
            {
                if ((_Grant_Category == null))
                {
                    _Grant_Category = base.CreateObjectSet<Grant_Category>("Grant_Category");
                }
                return _Grant_Category;
            }
        }
        private ObjectSet<Grant_Category> _Grant_Category;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Grant_Daily> Grant_Daily
        {
            get
            {
                if ((_Grant_Daily == null))
                {
                    _Grant_Daily = base.CreateObjectSet<Grant_Daily>("Grant_Daily");
                }
                return _Grant_Daily;
            }
        }
        private ObjectSet<Grant_Daily> _Grant_Daily;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Grant_GrantType> Grant_GrantType
        {
            get
            {
                if ((_Grant_GrantType == null))
                {
                    _Grant_GrantType = base.CreateObjectSet<Grant_GrantType>("Grant_GrantType");
                }
                return _Grant_GrantType;
            }
        }
        private ObjectSet<Grant_GrantType> _Grant_GrantType;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Grant_Activity> Grant_Activity
        {
            get
            {
                if ((_Grant_Activity == null))
                {
                    _Grant_Activity = base.CreateObjectSet<Grant_Activity>("Grant_Activity");
                }
                return _Grant_Activity;
            }
        }
        private ObjectSet<Grant_Activity> _Grant_Activity;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Person> People
        {
            get
            {
                if ((_People == null))
                {
                    _People = base.CreateObjectSet<Person>("People");
                }
                return _People;
            }
        }
        private ObjectSet<Person> _People;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Grant_vActivityApprover> Grant_vActivityApprover
        {
            get
            {
                if ((_Grant_vActivityApprover == null))
                {
                    _Grant_vActivityApprover = base.CreateObjectSet<Grant_vActivityApprover>("Grant_vActivityApprover");
                }
                return _Grant_vActivityApprover;
            }
        }
        private ObjectSet<Grant_vActivityApprover> _Grant_vActivityApprover;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Shift> Shifts
        {
            get
            {
                if ((_Shifts == null))
                {
                    _Shifts = base.CreateObjectSet<Shift>("Shifts");
                }
                return _Shifts;
            }
        }
        private ObjectSet<Shift> _Shifts;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Grant_Category EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGrant_Category(Grant_Category grant_Category)
        {
            base.AddObject("Grant_Category", grant_Category);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Grant_Daily EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGrant_Daily(Grant_Daily grant_Daily)
        {
            base.AddObject("Grant_Daily", grant_Daily);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Grant_GrantType EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGrant_GrantType(Grant_GrantType grant_GrantType)
        {
            base.AddObject("Grant_GrantType", grant_GrantType);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Grant_Activity EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGrant_Activity(Grant_Activity grant_Activity)
        {
            base.AddObject("Grant_Activity", grant_Activity);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the People EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPeople(Person person)
        {
            base.AddObject("People", person);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Grant_vActivityApprover EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGrant_vActivityApprover(Grant_vActivityApprover grant_vActivityApprover)
        {
            base.AddObject("Grant_vActivityApprover", grant_vActivityApprover);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Shifts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToShifts(Shift shift)
        {
            base.AddObject("Shifts", shift);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GrantModel", Name="Grant_Activity")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Grant_Activity : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Grant_Activity object.
        /// </summary>
        /// <param name="activityID">Initial value of the ActivityID property.</param>
        /// <param name="dailyID">Initial value of the DailyID property.</param>
        /// <param name="categoryID">Initial value of the CategoryID property.</param>
        public static Grant_Activity CreateGrant_Activity(global::System.Int32 activityID, global::System.Int32 dailyID, global::System.Int32 categoryID)
        {
            Grant_Activity grant_Activity = new Grant_Activity();
            grant_Activity.ActivityID = activityID;
            grant_Activity.DailyID = dailyID;
            grant_Activity.CategoryID = categoryID;
            return grant_Activity;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ActivityID
        {
            get
            {
                return _ActivityID;
            }
            set
            {
                if (_ActivityID != value)
                {
                    OnActivityIDChanging(value);
                    ReportPropertyChanging("ActivityID");
                    _ActivityID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ActivityID");
                    OnActivityIDChanged();
                }
            }
        }
        private global::System.Int32 _ActivityID;
        partial void OnActivityIDChanging(global::System.Int32 value);
        partial void OnActivityIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DailyID
        {
            get
            {
                return _DailyID;
            }
            set
            {
                OnDailyIDChanging(value);
                ReportPropertyChanging("DailyID");
                _DailyID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DailyID");
                OnDailyIDChanged();
            }
        }
        private global::System.Int32 _DailyID;
        partial void OnDailyIDChanging(global::System.Int32 value);
        partial void OnDailyIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CategoryID
        {
            get
            {
                return _CategoryID;
            }
            set
            {
                OnCategoryIDChanging(value);
                ReportPropertyChanging("CategoryID");
                _CategoryID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CategoryID");
                OnCategoryIDChanged();
            }
        }
        private global::System.Int32 _CategoryID;
        partial void OnCategoryIDChanging(global::System.Int32 value);
        partial void OnCategoryIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Notes
        {
            get
            {
                return _Notes;
            }
            set
            {
                OnNotesChanging(value);
                ReportPropertyChanging("Notes");
                _Notes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Notes");
                OnNotesChanged();
            }
        }
        private global::System.String _Notes;
        partial void OnNotesChanging(global::System.String value);
        partial void OnNotesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EnteredDate
        {
            get
            {
                return _EnteredDate;
            }
            set
            {
                OnEnteredDateChanging(value);
                ReportPropertyChanging("EnteredDate");
                _EnteredDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EnteredDate");
                OnEnteredDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _EnteredDate;
        partial void OnEnteredDateChanging(Nullable<global::System.DateTime> value);
        partial void OnEnteredDateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GrantModel", "FK_Grant_Activity_Grant_Category", "Grant_Category")]
        public Grant_Category Grant_Category
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Grant_Category>("GrantModel.FK_Grant_Activity_Grant_Category", "Grant_Category").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Grant_Category>("GrantModel.FK_Grant_Activity_Grant_Category", "Grant_Category").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Grant_Category> Grant_CategoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Grant_Category>("GrantModel.FK_Grant_Activity_Grant_Category", "Grant_Category");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Grant_Category>("GrantModel.FK_Grant_Activity_Grant_Category", "Grant_Category", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GrantModel", "FK_Grant_Activity_Grant_Daily", "Grant_Daily")]
        public Grant_Daily Grant_Daily
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Grant_Daily>("GrantModel.FK_Grant_Activity_Grant_Daily", "Grant_Daily").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Grant_Daily>("GrantModel.FK_Grant_Activity_Grant_Daily", "Grant_Daily").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Grant_Daily> Grant_DailyReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Grant_Daily>("GrantModel.FK_Grant_Activity_Grant_Daily", "Grant_Daily");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Grant_Daily>("GrantModel.FK_Grant_Activity_Grant_Daily", "Grant_Daily", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GrantModel", Name="Grant_Category")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Grant_Category : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Grant_Category object.
        /// </summary>
        /// <param name="categoryID">Initial value of the CategoryID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Grant_Category CreateGrant_Category(global::System.Int32 categoryID, global::System.String name)
        {
            Grant_Category grant_Category = new Grant_Category();
            grant_Category.CategoryID = categoryID;
            grant_Category.Name = name;
            return grant_Category;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CategoryID
        {
            get
            {
                return _CategoryID;
            }
            set
            {
                if (_CategoryID != value)
                {
                    OnCategoryIDChanging(value);
                    ReportPropertyChanging("CategoryID");
                    _CategoryID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CategoryID");
                    OnCategoryIDChanged();
                }
            }
        }
        private global::System.Int32 _CategoryID;
        partial void OnCategoryIDChanging(global::System.Int32 value);
        partial void OnCategoryIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GrantModel", "FK_Grant_Activity_Grant_Category", "Grant_Activity")]
        public EntityCollection<Grant_Activity> Grant_Activity
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Grant_Activity>("GrantModel.FK_Grant_Activity_Grant_Category", "Grant_Activity");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Grant_Activity>("GrantModel.FK_Grant_Activity_Grant_Category", "Grant_Activity", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GrantModel", Name="Grant_Daily")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Grant_Daily : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Grant_Daily object.
        /// </summary>
        /// <param name="adminDailyID">Initial value of the AdminDailyID property.</param>
        /// <param name="appEntityID">Initial value of the AppEntityID property.</param>
        /// <param name="grantTypeID">Initial value of the GrantTypeID property.</param>
        /// <param name="dailyStart">Initial value of the DailyStart property.</param>
        /// <param name="dailyEnd">Initial value of the DailyEnd property.</param>
        /// <param name="enteredDate">Initial value of the EnteredDate property.</param>
        public static Grant_Daily CreateGrant_Daily(global::System.Int32 adminDailyID, global::System.Int32 appEntityID, global::System.Int32 grantTypeID, global::System.DateTime dailyStart, global::System.DateTime dailyEnd, global::System.DateTime enteredDate)
        {
            Grant_Daily grant_Daily = new Grant_Daily();
            grant_Daily.AdminDailyID = adminDailyID;
            grant_Daily.AppEntityID = appEntityID;
            grant_Daily.GrantTypeID = grantTypeID;
            grant_Daily.DailyStart = dailyStart;
            grant_Daily.DailyEnd = dailyEnd;
            grant_Daily.EnteredDate = enteredDate;
            return grant_Daily;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AdminDailyID
        {
            get
            {
                return _AdminDailyID;
            }
            set
            {
                if (_AdminDailyID != value)
                {
                    OnAdminDailyIDChanging(value);
                    ReportPropertyChanging("AdminDailyID");
                    _AdminDailyID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AdminDailyID");
                    OnAdminDailyIDChanged();
                }
            }
        }
        private global::System.Int32 _AdminDailyID;
        partial void OnAdminDailyIDChanging(global::System.Int32 value);
        partial void OnAdminDailyIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AppEntityID
        {
            get
            {
                return _AppEntityID;
            }
            set
            {
                OnAppEntityIDChanging(value);
                ReportPropertyChanging("AppEntityID");
                _AppEntityID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AppEntityID");
                OnAppEntityIDChanged();
            }
        }
        private global::System.Int32 _AppEntityID;
        partial void OnAppEntityIDChanging(global::System.Int32 value);
        partial void OnAppEntityIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GrantTypeID
        {
            get
            {
                return _GrantTypeID;
            }
            set
            {
                OnGrantTypeIDChanging(value);
                ReportPropertyChanging("GrantTypeID");
                _GrantTypeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GrantTypeID");
                OnGrantTypeIDChanged();
            }
        }
        private global::System.Int32 _GrantTypeID;
        partial void OnGrantTypeIDChanging(global::System.Int32 value);
        partial void OnGrantTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DailyStart
        {
            get
            {
                return _DailyStart;
            }
            set
            {
                OnDailyStartChanging(value);
                ReportPropertyChanging("DailyStart");
                _DailyStart = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DailyStart");
                OnDailyStartChanged();
            }
        }
        private global::System.DateTime _DailyStart;
        partial void OnDailyStartChanging(global::System.DateTime value);
        partial void OnDailyStartChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DailyEnd
        {
            get
            {
                return _DailyEnd;
            }
            set
            {
                OnDailyEndChanging(value);
                ReportPropertyChanging("DailyEnd");
                _DailyEnd = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DailyEnd");
                OnDailyEndChanged();
            }
        }
        private global::System.DateTime _DailyEnd;
        partial void OnDailyEndChanging(global::System.DateTime value);
        partial void OnDailyEndChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime EnteredDate
        {
            get
            {
                return _EnteredDate;
            }
            set
            {
                OnEnteredDateChanging(value);
                ReportPropertyChanging("EnteredDate");
                _EnteredDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EnteredDate");
                OnEnteredDateChanged();
            }
        }
        private global::System.DateTime _EnteredDate;
        partial void OnEnteredDateChanging(global::System.DateTime value);
        partial void OnEnteredDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> ApprovedFlag
        {
            get
            {
                return _ApprovedFlag;
            }
            set
            {
                OnApprovedFlagChanging(value);
                ReportPropertyChanging("ApprovedFlag");
                _ApprovedFlag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ApprovedFlag");
                OnApprovedFlagChanged();
            }
        }
        private Nullable<global::System.Boolean> _ApprovedFlag;
        partial void OnApprovedFlagChanging(Nullable<global::System.Boolean> value);
        partial void OnApprovedFlagChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> MoreInformationFlag
        {
            get
            {
                return _MoreInformationFlag;
            }
            set
            {
                OnMoreInformationFlagChanging(value);
                ReportPropertyChanging("MoreInformationFlag");
                _MoreInformationFlag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MoreInformationFlag");
                OnMoreInformationFlagChanged();
            }
        }
        private Nullable<global::System.Boolean> _MoreInformationFlag;
        partial void OnMoreInformationFlagChanging(Nullable<global::System.Boolean> value);
        partial void OnMoreInformationFlagChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AdminNotes
        {
            get
            {
                return _AdminNotes;
            }
            set
            {
                OnAdminNotesChanging(value);
                ReportPropertyChanging("AdminNotes");
                _AdminNotes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AdminNotes");
                OnAdminNotesChanged();
            }
        }
        private global::System.String _AdminNotes;
        partial void OnAdminNotesChanging(global::System.String value);
        partial void OnAdminNotesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ApprovedByID
        {
            get
            {
                return _ApprovedByID;
            }
            set
            {
                OnApprovedByIDChanging(value);
                ReportPropertyChanging("ApprovedByID");
                _ApprovedByID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ApprovedByID");
                OnApprovedByIDChanged();
            }
        }
        private Nullable<global::System.Int32> _ApprovedByID;
        partial void OnApprovedByIDChanging(Nullable<global::System.Int32> value);
        partial void OnApprovedByIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ApprovedDate
        {
            get
            {
                return _ApprovedDate;
            }
            set
            {
                OnApprovedDateChanging(value);
                ReportPropertyChanging("ApprovedDate");
                _ApprovedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ApprovedDate");
                OnApprovedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ApprovedDate;
        partial void OnApprovedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnApprovedDateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GrantModel", "FK_Grant_Daily_Grant_GrantType", "Grant_GrantType")]
        public Grant_GrantType Grant_GrantType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Grant_GrantType>("GrantModel.FK_Grant_Daily_Grant_GrantType", "Grant_GrantType").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Grant_GrantType>("GrantModel.FK_Grant_Daily_Grant_GrantType", "Grant_GrantType").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Grant_GrantType> Grant_GrantTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Grant_GrantType>("GrantModel.FK_Grant_Daily_Grant_GrantType", "Grant_GrantType");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Grant_GrantType>("GrantModel.FK_Grant_Daily_Grant_GrantType", "Grant_GrantType", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GrantModel", "FK_Grant_Activity_Grant_Daily", "Grant_Activity")]
        public EntityCollection<Grant_Activity> Grant_Activity
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Grant_Activity>("GrantModel.FK_Grant_Activity_Grant_Daily", "Grant_Activity");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Grant_Activity>("GrantModel.FK_Grant_Activity_Grant_Daily", "Grant_Activity", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GrantModel", "Daily_Person", "Person")]
        public Person Person
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Person>("GrantModel.Daily_Person", "Person").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Person>("GrantModel.Daily_Person", "Person").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Person> PersonReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Person>("GrantModel.Daily_Person", "Person");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Person>("GrantModel.Daily_Person", "Person", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GrantModel", "Grant_vActivityApproverGrant_Daily", "Grant_vActivityApprover")]
        public Grant_vActivityApprover Grant_vActivityApprover
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Grant_vActivityApprover>("GrantModel.Grant_vActivityApproverGrant_Daily", "Grant_vActivityApprover").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Grant_vActivityApprover>("GrantModel.Grant_vActivityApproverGrant_Daily", "Grant_vActivityApprover").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Grant_vActivityApprover> Grant_vActivityApproverReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Grant_vActivityApprover>("GrantModel.Grant_vActivityApproverGrant_Daily", "Grant_vActivityApprover");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Grant_vActivityApprover>("GrantModel.Grant_vActivityApproverGrant_Daily", "Grant_vActivityApprover", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GrantModel", Name="Grant_GrantType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Grant_GrantType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Grant_GrantType object.
        /// </summary>
        /// <param name="grantTypeID">Initial value of the GrantTypeID property.</param>
        /// <param name="visibleFlag">Initial value of the VisibleFlag property.</param>
        public static Grant_GrantType CreateGrant_GrantType(global::System.Int32 grantTypeID, global::System.Boolean visibleFlag)
        {
            Grant_GrantType grant_GrantType = new Grant_GrantType();
            grant_GrantType.GrantTypeID = grantTypeID;
            grant_GrantType.VisibleFlag = visibleFlag;
            return grant_GrantType;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GrantTypeID
        {
            get
            {
                return _GrantTypeID;
            }
            set
            {
                if (_GrantTypeID != value)
                {
                    OnGrantTypeIDChanging(value);
                    ReportPropertyChanging("GrantTypeID");
                    _GrantTypeID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("GrantTypeID");
                    OnGrantTypeIDChanged();
                }
            }
        }
        private global::System.Int32 _GrantTypeID;
        partial void OnGrantTypeIDChanging(global::System.Int32 value);
        partial void OnGrantTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GrantType
        {
            get
            {
                return _GrantType;
            }
            set
            {
                OnGrantTypeChanging(value);
                ReportPropertyChanging("GrantType");
                _GrantType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GrantType");
                OnGrantTypeChanged();
            }
        }
        private global::System.String _GrantType;
        partial void OnGrantTypeChanging(global::System.String value);
        partial void OnGrantTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean VisibleFlag
        {
            get
            {
                return _VisibleFlag;
            }
            set
            {
                OnVisibleFlagChanging(value);
                ReportPropertyChanging("VisibleFlag");
                _VisibleFlag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VisibleFlag");
                OnVisibleFlagChanged();
            }
        }
        private global::System.Boolean _VisibleFlag;
        partial void OnVisibleFlagChanging(global::System.Boolean value);
        partial void OnVisibleFlagChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GrantModel", "FK_Grant_Daily_Grant_GrantType", "Grant_Daily")]
        public EntityCollection<Grant_Daily> Grant_Daily
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Grant_Daily>("GrantModel.FK_Grant_Daily_Grant_GrantType", "Grant_Daily");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Grant_Daily>("GrantModel.FK_Grant_Daily_Grant_GrantType", "Grant_Daily", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GrantModel", Name="Grant_vActivityApprover")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Grant_vActivityApprover : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Grant_vActivityApprover object.
        /// </summary>
        /// <param name="appEntityID">Initial value of the AppEntityID property.</param>
        public static Grant_vActivityApprover CreateGrant_vActivityApprover(global::System.Int32 appEntityID)
        {
            Grant_vActivityApprover grant_vActivityApprover = new Grant_vActivityApprover();
            grant_vActivityApprover.AppEntityID = appEntityID;
            return grant_vActivityApprover;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AppEntityID
        {
            get
            {
                return _AppEntityID;
            }
            set
            {
                if (_AppEntityID != value)
                {
                    OnAppEntityIDChanging(value);
                    ReportPropertyChanging("AppEntityID");
                    _AppEntityID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AppEntityID");
                    OnAppEntityIDChanged();
                }
            }
        }
        private global::System.Int32 _AppEntityID;
        partial void OnAppEntityIDChanging(global::System.Int32 value);
        partial void OnAppEntityIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ApproveBy
        {
            get
            {
                return _ApproveBy;
            }
            set
            {
                OnApproveByChanging(value);
                ReportPropertyChanging("ApproveBy");
                _ApproveBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ApproveBy");
                OnApproveByChanged();
            }
        }
        private global::System.String _ApproveBy;
        partial void OnApproveByChanging(global::System.String value);
        partial void OnApproveByChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GrantModel", "Grant_vActivityApproverGrant_Daily", "Grant_Daily")]
        public EntityCollection<Grant_Daily> Grant_Daily
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Grant_Daily>("GrantModel.Grant_vActivityApproverGrant_Daily", "Grant_Daily");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Grant_Daily>("GrantModel.Grant_vActivityApproverGrant_Daily", "Grant_Daily", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GrantModel", Name="Person")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Person : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Person object.
        /// </summary>
        /// <param name="appEntityID">Initial value of the AppEntityID property.</param>
        public static Person CreatePerson(global::System.Int32 appEntityID)
        {
            Person person = new Person();
            person.AppEntityID = appEntityID;
            return person;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AppEntityID
        {
            get
            {
                return _AppEntityID;
            }
            set
            {
                if (_AppEntityID != value)
                {
                    OnAppEntityIDChanging(value);
                    ReportPropertyChanging("AppEntityID");
                    _AppEntityID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AppEntityID");
                    OnAppEntityIDChanged();
                }
            }
        }
        private global::System.Int32 _AppEntityID;
        partial void OnAppEntityIDChanging(global::System.Int32 value);
        partial void OnAppEntityIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PersonTypeID
        {
            get
            {
                return _PersonTypeID;
            }
            set
            {
                OnPersonTypeIDChanging(value);
                ReportPropertyChanging("PersonTypeID");
                _PersonTypeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PersonTypeID");
                OnPersonTypeIDChanged();
            }
        }
        private Nullable<global::System.Int32> _PersonTypeID;
        partial void OnPersonTypeIDChanging(Nullable<global::System.Int32> value);
        partial void OnPersonTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MiddleName
        {
            get
            {
                return _MiddleName;
            }
            set
            {
                OnMiddleNameChanging(value);
                ReportPropertyChanging("MiddleName");
                _MiddleName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MiddleName");
                OnMiddleNameChanged();
            }
        }
        private global::System.String _MiddleName;
        partial void OnMiddleNameChanging(global::System.String value);
        partial void OnMiddleNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Suffix
        {
            get
            {
                return _Suffix;
            }
            set
            {
                OnSuffixChanging(value);
                ReportPropertyChanging("Suffix");
                _Suffix = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Suffix");
                OnSuffixChanged();
            }
        }
        private global::System.String _Suffix;
        partial void OnSuffixChanging(global::System.String value);
        partial void OnSuffixChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> rowguid
        {
            get
            {
                return _rowguid;
            }
            set
            {
                OnrowguidChanging(value);
                ReportPropertyChanging("rowguid");
                _rowguid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("rowguid");
                OnrowguidChanged();
            }
        }
        private Nullable<global::System.Guid> _rowguid;
        partial void OnrowguidChanging(Nullable<global::System.Guid> value);
        partial void OnrowguidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return _ModifiedDate;
            }
            set
            {
                OnModifiedDateChanging(value);
                ReportPropertyChanging("ModifiedDate");
                _ModifiedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedDate");
                OnModifiedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModifiedDate;
        partial void OnModifiedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnModifiedDateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GrantModel", "Daily_Person", "Grant_Daily")]
        public EntityCollection<Grant_Daily> Grant_Daily
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Grant_Daily>("GrantModel.Daily_Person", "Grant_Daily");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Grant_Daily>("GrantModel.Daily_Person", "Grant_Daily", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GrantModel", "FK_User_User_Person_Person", "User_User")]
        public User User_User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("GrantModel.FK_User_User_Person_Person", "User_User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("GrantModel.FK_User_User_Person_Person", "User_User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> User_UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("GrantModel.FK_User_User_Person_Person", "User_User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("GrantModel.FK_User_User_Person_Person", "User_User", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GrantModel", Name="Shift")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Shift : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Shift object.
        /// </summary>
        /// <param name="shiftID">Initial value of the ShiftID property.</param>
        public static Shift CreateShift(global::System.Int32 shiftID)
        {
            Shift shift = new Shift();
            shift.ShiftID = shiftID;
            return shift;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ShiftID
        {
            get
            {
                return _ShiftID;
            }
            set
            {
                if (_ShiftID != value)
                {
                    OnShiftIDChanging(value);
                    ReportPropertyChanging("ShiftID");
                    _ShiftID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ShiftID");
                    OnShiftIDChanged();
                }
            }
        }
        private global::System.Int32 _ShiftID;
        partial void OnShiftIDChanging(global::System.Int32 value);
        partial void OnShiftIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.TimeSpan> StartTime
        {
            get
            {
                return _StartTime;
            }
            set
            {
                OnStartTimeChanging(value);
                ReportPropertyChanging("StartTime");
                _StartTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartTime");
                OnStartTimeChanged();
            }
        }
        private Nullable<global::System.TimeSpan> _StartTime;
        partial void OnStartTimeChanging(Nullable<global::System.TimeSpan> value);
        partial void OnStartTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.TimeSpan> EndTime
        {
            get
            {
                return _EndTime;
            }
            set
            {
                OnEndTimeChanging(value);
                ReportPropertyChanging("EndTime");
                _EndTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndTime");
                OnEndTimeChanged();
            }
        }
        private Nullable<global::System.TimeSpan> _EndTime;
        partial void OnEndTimeChanging(Nullable<global::System.TimeSpan> value);
        partial void OnEndTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return _ModifiedDate;
            }
            set
            {
                OnModifiedDateChanging(value);
                ReportPropertyChanging("ModifiedDate");
                _ModifiedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedDate");
                OnModifiedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModifiedDate;
        partial void OnModifiedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnModifiedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MainframCode
        {
            get
            {
                return _MainframCode;
            }
            set
            {
                OnMainframCodeChanging(value);
                ReportPropertyChanging("MainframCode");
                _MainframCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MainframCode");
                OnMainframCodeChanged();
            }
        }
        private global::System.String _MainframCode;
        partial void OnMainframCodeChanging(global::System.String value);
        partial void OnMainframCodeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GrantModel", "ShiftUser", "User")]
        public EntityCollection<User> Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<User>("GrantModel.ShiftUser", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<User>("GrantModel.ShiftUser", "User", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GrantModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="appEntityID">Initial value of the AppEntityID property.</param>
        /// <param name="hireDate">Initial value of the HireDate property.</param>
        /// <param name="shiftID">Initial value of the ShiftID property.</param>
        public static User CreateUser(global::System.Int32 appEntityID, global::System.DateTime hireDate, global::System.Int32 shiftID)
        {
            User user = new User();
            user.AppEntityID = appEntityID;
            user.HireDate = hireDate;
            user.ShiftID = shiftID;
            return user;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AppEntityID
        {
            get
            {
                return _AppEntityID;
            }
            set
            {
                if (_AppEntityID != value)
                {
                    OnAppEntityIDChanging(value);
                    ReportPropertyChanging("AppEntityID");
                    _AppEntityID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AppEntityID");
                    OnAppEntityIDChanged();
                }
            }
        }
        private global::System.Int32 _AppEntityID;
        partial void OnAppEntityIDChanging(global::System.Int32 value);
        partial void OnAppEntityIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PIN
        {
            get
            {
                return _PIN;
            }
            set
            {
                OnPINChanging(value);
                ReportPropertyChanging("PIN");
                _PIN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PIN");
                OnPINChanged();
            }
        }
        private global::System.String _PIN;
        partial void OnPINChanging(global::System.String value);
        partial void OnPINChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SAP
        {
            get
            {
                return _SAP;
            }
            set
            {
                OnSAPChanging(value);
                ReportPropertyChanging("SAP");
                _SAP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SAP");
                OnSAPChanged();
            }
        }
        private global::System.String _SAP;
        partial void OnSAPChanging(global::System.String value);
        partial void OnSAPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CADID
        {
            get
            {
                return _CADID;
            }
            set
            {
                OnCADIDChanging(value);
                ReportPropertyChanging("CADID");
                _CADID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CADID");
                OnCADIDChanged();
            }
        }
        private Nullable<global::System.Int32> _CADID;
        partial void OnCADIDChanging(Nullable<global::System.Int32> value);
        partial void OnCADIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> JobTitleID
        {
            get
            {
                return _JobTitleID;
            }
            set
            {
                OnJobTitleIDChanging(value);
                ReportPropertyChanging("JobTitleID");
                _JobTitleID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("JobTitleID");
                OnJobTitleIDChanged();
            }
        }
        private Nullable<global::System.Int32> _JobTitleID;
        partial void OnJobTitleIDChanging(Nullable<global::System.Int32> value);
        partial void OnJobTitleIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ClassificationID
        {
            get
            {
                return _ClassificationID;
            }
            set
            {
                OnClassificationIDChanging(value);
                ReportPropertyChanging("ClassificationID");
                _ClassificationID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClassificationID");
                OnClassificationIDChanged();
            }
        }
        private Nullable<global::System.Int32> _ClassificationID;
        partial void OnClassificationIDChanging(Nullable<global::System.Int32> value);
        partial void OnClassificationIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Badge
        {
            get
            {
                return _Badge;
            }
            set
            {
                OnBadgeChanging(value);
                ReportPropertyChanging("Badge");
                _Badge = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Badge");
                OnBadgeChanged();
            }
        }
        private global::System.String _Badge;
        partial void OnBadgeChanging(global::System.String value);
        partial void OnBadgeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DOB
        {
            get
            {
                return _DOB;
            }
            set
            {
                OnDOBChanging(value);
                ReportPropertyChanging("DOB");
                _DOB = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DOB");
                OnDOBChanged();
            }
        }
        private Nullable<global::System.DateTime> _DOB;
        partial void OnDOBChanging(Nullable<global::System.DateTime> value);
        partial void OnDOBChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Gender
        {
            get
            {
                return _Gender;
            }
            set
            {
                OnGenderChanging(value);
                ReportPropertyChanging("Gender");
                _Gender = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Gender");
                OnGenderChanged();
            }
        }
        private global::System.String _Gender;
        partial void OnGenderChanging(global::System.String value);
        partial void OnGenderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ethnicty
        {
            get
            {
                return _Ethnicty;
            }
            set
            {
                OnEthnictyChanging(value);
                ReportPropertyChanging("Ethnicty");
                _Ethnicty = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ethnicty");
                OnEthnictyChanged();
            }
        }
        private global::System.String _Ethnicty;
        partial void OnEthnictyChanging(global::System.String value);
        partial void OnEthnictyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MaritalStatus
        {
            get
            {
                return _MaritalStatus;
            }
            set
            {
                OnMaritalStatusChanging(value);
                ReportPropertyChanging("MaritalStatus");
                _MaritalStatus = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MaritalStatus");
                OnMaritalStatusChanged();
            }
        }
        private global::System.String _MaritalStatus;
        partial void OnMaritalStatusChanging(global::System.String value);
        partial void OnMaritalStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime HireDate
        {
            get
            {
                return _HireDate;
            }
            set
            {
                OnHireDateChanging(value);
                ReportPropertyChanging("HireDate");
                _HireDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HireDate");
                OnHireDateChanged();
            }
        }
        private global::System.DateTime _HireDate;
        partial void OnHireDateChanging(global::System.DateTime value);
        partial void OnHireDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> rowguid
        {
            get
            {
                return _rowguid;
            }
            set
            {
                OnrowguidChanging(value);
                ReportPropertyChanging("rowguid");
                _rowguid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("rowguid");
                OnrowguidChanged();
            }
        }
        private Nullable<global::System.Guid> _rowguid;
        partial void OnrowguidChanging(Nullable<global::System.Guid> value);
        partial void OnrowguidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> WorksheetVisibleFlag
        {
            get
            {
                return _WorksheetVisibleFlag;
            }
            set
            {
                OnWorksheetVisibleFlagChanging(value);
                ReportPropertyChanging("WorksheetVisibleFlag");
                _WorksheetVisibleFlag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WorksheetVisibleFlag");
                OnWorksheetVisibleFlagChanged();
            }
        }
        private Nullable<global::System.Boolean> _WorksheetVisibleFlag;
        partial void OnWorksheetVisibleFlagChanging(Nullable<global::System.Boolean> value);
        partial void OnWorksheetVisibleFlagChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return _ModifiedDate;
            }
            set
            {
                OnModifiedDateChanging(value);
                ReportPropertyChanging("ModifiedDate");
                _ModifiedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedDate");
                OnModifiedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModifiedDate;
        partial void OnModifiedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnModifiedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> OfficeID
        {
            get
            {
                return _OfficeID;
            }
            set
            {
                OnOfficeIDChanging(value);
                ReportPropertyChanging("OfficeID");
                _OfficeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OfficeID");
                OnOfficeIDChanged();
            }
        }
        private Nullable<global::System.Int32> _OfficeID;
        partial void OnOfficeIDChanging(Nullable<global::System.Int32> value);
        partial void OnOfficeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SectionID
        {
            get
            {
                return _SectionID;
            }
            set
            {
                OnSectionIDChanging(value);
                ReportPropertyChanging("SectionID");
                _SectionID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SectionID");
                OnSectionIDChanged();
            }
        }
        private Nullable<global::System.Int32> _SectionID;
        partial void OnSectionIDChanging(Nullable<global::System.Int32> value);
        partial void OnSectionIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RDID
        {
            get
            {
                return _RDID;
            }
            set
            {
                OnRDIDChanging(value);
                ReportPropertyChanging("RDID");
                _RDID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RDID");
                OnRDIDChanged();
            }
        }
        private Nullable<global::System.Int32> _RDID;
        partial void OnRDIDChanging(Nullable<global::System.Int32> value);
        partial void OnRDIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ShiftID
        {
            get
            {
                return _ShiftID;
            }
            set
            {
                OnShiftIDChanging(value);
                ReportPropertyChanging("ShiftID");
                _ShiftID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ShiftID");
                OnShiftIDChanged();
            }
        }
        private global::System.Int32 _ShiftID;
        partial void OnShiftIDChanging(global::System.Int32 value);
        partial void OnShiftIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> WorkStatusID
        {
            get
            {
                return _WorkStatusID;
            }
            set
            {
                OnWorkStatusIDChanging(value);
                ReportPropertyChanging("WorkStatusID");
                _WorkStatusID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WorkStatusID");
                OnWorkStatusIDChanged();
            }
        }
        private Nullable<global::System.Int32> _WorkStatusID;
        partial void OnWorkStatusIDChanging(Nullable<global::System.Int32> value);
        partial void OnWorkStatusIDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GrantModel", "FK_User_User_Person_Person", "Person")]
        public Person Person_Person
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Person>("GrantModel.FK_User_User_Person_Person", "Person").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Person>("GrantModel.FK_User_User_Person_Person", "Person").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Person> Person_PersonReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Person>("GrantModel.FK_User_User_Person_Person", "Person");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Person>("GrantModel.FK_User_User_Person_Person", "Person", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GrantModel", "ShiftUser", "Shift")]
        public Shift Shift
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Shift>("GrantModel.ShiftUser", "Shift").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Shift>("GrantModel.ShiftUser", "Shift").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Shift> ShiftReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Shift>("GrantModel.ShiftUser", "Shift");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Shift>("GrantModel.ShiftUser", "Shift", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
