//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("SIAWebLinksModel", "FK_SIA_WebLinks_SIA_WebCategories", "SIA_WebCategories", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SIAWebLinksBusinessLayer.WebCategories), "SIA_WebLinks", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SIAWebLinksBusinessLayer.WebLinks), true)]
[assembly: EdmRelationshipAttribute("SIAWebLinksModel", "FK_Activity_ActivityLog_SIA_WebLinks", "WebLinks", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SIAWebLinksBusinessLayer.WebLinks), "Activity_ActivityLog", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SIAWebLinksBusinessLayer.ActivityLog), true)]
[assembly: EdmRelationshipAttribute("SIAWebLinksModel", "FK_Activity_ActivityLog_SIA_WebLinks1", "WebLinks", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SIAWebLinksBusinessLayer.WebLinks), "Activity_ActivityLog", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SIAWebLinksBusinessLayer.ActivityLog), true)]

#endregion

namespace SIAWebLinksBusinessLayer
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class WebLinksEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new WebLinksEntities object using the connection string found in the 'WebLinksEntities' section of the application configuration file.
        /// </summary>
        public WebLinksEntities() : base("name=WebLinksEntities", "WebLinksEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new WebLinksEntities object.
        /// </summary>
        public WebLinksEntities(string connectionString) : base(connectionString, "WebLinksEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new WebLinksEntities object.
        /// </summary>
        public WebLinksEntities(EntityConnection connection) : base(connection, "WebLinksEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<WebCategories> WebCategories
        {
            get
            {
                if ((_WebCategories == null))
                {
                    _WebCategories = base.CreateObjectSet<WebCategories>("WebCategories");
                }
                return _WebCategories;
            }
        }
        private ObjectSet<WebCategories> _WebCategories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<WebLinks> WebLinks
        {
            get
            {
                if ((_WebLinks == null))
                {
                    _WebLinks = base.CreateObjectSet<WebLinks>("WebLinks");
                }
                return _WebLinks;
            }
        }
        private ObjectSet<WebLinks> _WebLinks;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ActivityLog> ActivityLogs
        {
            get
            {
                if ((_ActivityLogs == null))
                {
                    _ActivityLogs = base.CreateObjectSet<ActivityLog>("ActivityLogs");
                }
                return _ActivityLogs;
            }
        }
        private ObjectSet<ActivityLog> _ActivityLogs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SearchFor> SearchFors
        {
            get
            {
                if ((_SearchFors == null))
                {
                    _SearchFors = base.CreateObjectSet<SearchFor>("SearchFors");
                }
                return _SearchFors;
            }
        }
        private ObjectSet<SearchFor> _SearchFors;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the WebCategories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWebCategories(WebCategories webCategories)
        {
            base.AddObject("WebCategories", webCategories);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the WebLinks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWebLinks(WebLinks webLinks)
        {
            base.AddObject("WebLinks", webLinks);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ActivityLogs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToActivityLogs(ActivityLog activityLog)
        {
            base.AddObject("ActivityLogs", activityLog);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SearchFors EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSearchFors(SearchFor searchFor)
        {
            base.AddObject("SearchFors", searchFor);
        }

        #endregion

        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<spGetAllSIAWebLinks_Result> spGetAllSIAWebLinks()
        {
            return base.ExecuteFunction<spGetAllSIAWebLinks_Result>("spGetAllSIAWebLinks");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="pin">No Metadata Documentation available.</param>
        public ObjectResult<MyTopWebLinks_Result> Activity_spMyTopWebLinks(global::System.String pin)
        {
            ObjectParameter pinParameter;
            if (pin != null)
            {
                pinParameter = new ObjectParameter("Pin", pin);
            }
            else
            {
                pinParameter = new ObjectParameter("Pin", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<MyTopWebLinks_Result>("Activity_spMyTopWebLinks", pinParameter);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SIAWebLinksModel", Name="ActivityLog")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ActivityLog : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ActivityLog object.
        /// </summary>
        /// <param name="activityLogID">Initial value of the ActivityLogID property.</param>
        /// <param name="webAppID">Initial value of the WebAppID property.</param>
        public static ActivityLog CreateActivityLog(global::System.Int32 activityLogID, global::System.Int32 webAppID)
        {
            ActivityLog activityLog = new ActivityLog();
            activityLog.ActivityLogID = activityLogID;
            activityLog.WebAppID = webAppID;
            return activityLog;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ActivityLogID
        {
            get
            {
                return _ActivityLogID;
            }
            set
            {
                if (_ActivityLogID != value)
                {
                    OnActivityLogIDChanging(value);
                    ReportPropertyChanging("ActivityLogID");
                    _ActivityLogID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ActivityLogID");
                    OnActivityLogIDChanged();
                }
            }
        }
        private global::System.Int32 _ActivityLogID;
        partial void OnActivityLogIDChanging(global::System.Int32 value);
        partial void OnActivityLogIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 WebAppID
        {
            get
            {
                return _WebAppID;
            }
            set
            {
                OnWebAppIDChanging(value);
                ReportPropertyChanging("WebAppID");
                _WebAppID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WebAppID");
                OnWebAppIDChanged();
            }
        }
        private global::System.Int32 _WebAppID;
        partial void OnWebAppIDChanging(global::System.Int32 value);
        partial void OnWebAppIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AppEntityID
        {
            get
            {
                return _AppEntityID;
            }
            set
            {
                OnAppEntityIDChanging(value);
                ReportPropertyChanging("AppEntityID");
                _AppEntityID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AppEntityID");
                OnAppEntityIDChanged();
            }
        }
        private Nullable<global::System.Int32> _AppEntityID;
        partial void OnAppEntityIDChanging(Nullable<global::System.Int32> value);
        partial void OnAppEntityIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> WebLinkID
        {
            get
            {
                return _WebLinkID;
            }
            set
            {
                OnWebLinkIDChanging(value);
                ReportPropertyChanging("WebLinkID");
                _WebLinkID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WebLinkID");
                OnWebLinkIDChanged();
            }
        }
        private Nullable<global::System.Int32> _WebLinkID;
        partial void OnWebLinkIDChanging(Nullable<global::System.Int32> value);
        partial void OnWebLinkIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Link
        {
            get
            {
                return _Link;
            }
            set
            {
                OnLinkChanging(value);
                ReportPropertyChanging("Link");
                _Link = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Link");
                OnLinkChanged();
            }
        }
        private global::System.String _Link;
        partial void OnLinkChanging(global::System.String value);
        partial void OnLinkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String WebPage
        {
            get
            {
                return _WebPage;
            }
            set
            {
                OnWebPageChanging(value);
                ReportPropertyChanging("WebPage");
                _WebPage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("WebPage");
                OnWebPageChanged();
            }
        }
        private global::System.String _WebPage;
        partial void OnWebPageChanging(global::System.String value);
        partial void OnWebPageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ClickedDatetime
        {
            get
            {
                return _ClickedDatetime;
            }
            set
            {
                OnClickedDatetimeChanging(value);
                ReportPropertyChanging("ClickedDatetime");
                _ClickedDatetime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClickedDatetime");
                OnClickedDatetimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _ClickedDatetime;
        partial void OnClickedDatetimeChanging(Nullable<global::System.DateTime> value);
        partial void OnClickedDatetimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Flagged
        {
            get
            {
                return _Flagged;
            }
            set
            {
                OnFlaggedChanging(value);
                ReportPropertyChanging("Flagged");
                _Flagged = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Flagged");
                OnFlaggedChanged();
            }
        }
        private Nullable<global::System.Boolean> _Flagged;
        partial void OnFlaggedChanging(Nullable<global::System.Boolean> value);
        partial void OnFlaggedChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SIAWebLinksModel", "FK_Activity_ActivityLog_SIA_WebLinks", "WebLinks")]
        public WebLinks SIA_WebLinks
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<WebLinks>("SIAWebLinksModel.FK_Activity_ActivityLog_SIA_WebLinks", "WebLinks").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<WebLinks>("SIAWebLinksModel.FK_Activity_ActivityLog_SIA_WebLinks", "WebLinks").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<WebLinks> SIA_WebLinksReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<WebLinks>("SIAWebLinksModel.FK_Activity_ActivityLog_SIA_WebLinks", "WebLinks");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<WebLinks>("SIAWebLinksModel.FK_Activity_ActivityLog_SIA_WebLinks", "WebLinks", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SIAWebLinksModel", "FK_Activity_ActivityLog_SIA_WebLinks1", "WebLinks")]
        public WebLinks SIA_WebLinks1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<WebLinks>("SIAWebLinksModel.FK_Activity_ActivityLog_SIA_WebLinks1", "WebLinks").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<WebLinks>("SIAWebLinksModel.FK_Activity_ActivityLog_SIA_WebLinks1", "WebLinks").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<WebLinks> SIA_WebLinks1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<WebLinks>("SIAWebLinksModel.FK_Activity_ActivityLog_SIA_WebLinks1", "WebLinks");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<WebLinks>("SIAWebLinksModel.FK_Activity_ActivityLog_SIA_WebLinks1", "WebLinks", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SIAWebLinksModel", Name="SearchFor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SearchFor : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SearchFor object.
        /// </summary>
        /// <param name="activitySearchID">Initial value of the ActivitySearchID property.</param>
        /// <param name="appEntityID">Initial value of the AppEntityID property.</param>
        /// <param name="searchForID">Initial value of the SearchForID property.</param>
        /// <param name="searchDateTime">Initial value of the SearchDateTime property.</param>
        public static SearchFor CreateSearchFor(global::System.Int32 activitySearchID, global::System.Int32 appEntityID, global::System.Int32 searchForID, global::System.DateTime searchDateTime)
        {
            SearchFor searchFor = new SearchFor();
            searchFor.ActivitySearchID = activitySearchID;
            searchFor.AppEntityID = appEntityID;
            searchFor.SearchForID = searchForID;
            searchFor.SearchDateTime = searchDateTime;
            return searchFor;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ActivitySearchID
        {
            get
            {
                return _ActivitySearchID;
            }
            set
            {
                if (_ActivitySearchID != value)
                {
                    OnActivitySearchIDChanging(value);
                    ReportPropertyChanging("ActivitySearchID");
                    _ActivitySearchID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ActivitySearchID");
                    OnActivitySearchIDChanged();
                }
            }
        }
        private global::System.Int32 _ActivitySearchID;
        partial void OnActivitySearchIDChanging(global::System.Int32 value);
        partial void OnActivitySearchIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AppEntityID
        {
            get
            {
                return _AppEntityID;
            }
            set
            {
                OnAppEntityIDChanging(value);
                ReportPropertyChanging("AppEntityID");
                _AppEntityID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AppEntityID");
                OnAppEntityIDChanged();
            }
        }
        private global::System.Int32 _AppEntityID;
        partial void OnAppEntityIDChanging(global::System.Int32 value);
        partial void OnAppEntityIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SearchForID
        {
            get
            {
                return _SearchForID;
            }
            set
            {
                OnSearchForIDChanging(value);
                ReportPropertyChanging("SearchForID");
                _SearchForID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SearchForID");
                OnSearchForIDChanged();
            }
        }
        private global::System.Int32 _SearchForID;
        partial void OnSearchForIDChanging(global::System.Int32 value);
        partial void OnSearchForIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime SearchDateTime
        {
            get
            {
                return _SearchDateTime;
            }
            set
            {
                OnSearchDateTimeChanging(value);
                ReportPropertyChanging("SearchDateTime");
                _SearchDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SearchDateTime");
                OnSearchDateTimeChanged();
            }
        }
        private global::System.DateTime _SearchDateTime;
        partial void OnSearchDateTimeChanging(global::System.DateTime value);
        partial void OnSearchDateTimeChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SIAWebLinksModel", Name="WebCategories")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class WebCategories : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new WebCategories object.
        /// </summary>
        /// <param name="webCategoriesID">Initial value of the WebCategoriesID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static WebCategories CreateWebCategories(global::System.Int32 webCategoriesID, global::System.String name)
        {
            WebCategories webCategories = new WebCategories();
            webCategories.WebCategoriesID = webCategoriesID;
            webCategories.Name = name;
            return webCategories;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 WebCategoriesID
        {
            get
            {
                return _WebCategoriesID;
            }
            set
            {
                if (_WebCategoriesID != value)
                {
                    OnWebCategoriesIDChanging(value);
                    ReportPropertyChanging("WebCategoriesID");
                    _WebCategoriesID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("WebCategoriesID");
                    OnWebCategoriesIDChanged();
                }
            }
        }
        private global::System.Int32 _WebCategoriesID;
        partial void OnWebCategoriesIDChanging(global::System.Int32 value);
        partial void OnWebCategoriesIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SIAWebLinksModel", "FK_SIA_WebLinks_SIA_WebCategories", "SIA_WebLinks")]
        public EntityCollection<WebLinks> SIA_WebLinks
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<WebLinks>("SIAWebLinksModel.FK_SIA_WebLinks_SIA_WebCategories", "SIA_WebLinks");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<WebLinks>("SIAWebLinksModel.FK_SIA_WebLinks_SIA_WebCategories", "SIA_WebLinks", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SIAWebLinksModel", Name="WebLinks")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class WebLinks : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new WebLinks object.
        /// </summary>
        /// <param name="webLinkID">Initial value of the WebLinkID property.</param>
        /// <param name="webCategoryID">Initial value of the WebCategoryID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="webLink">Initial value of the WebLink property.</param>
        /// <param name="visibleFlag">Initial value of the VisibleFlag property.</param>
        /// <param name="needAuthorizationFlag">Initial value of the NeedAuthorizationFlag property.</param>
        public static WebLinks CreateWebLinks(global::System.Int32 webLinkID, global::System.Int32 webCategoryID, global::System.String name, global::System.String webLink, global::System.Boolean visibleFlag, global::System.Boolean needAuthorizationFlag)
        {
            WebLinks webLinks = new WebLinks();
            webLinks.WebLinkID = webLinkID;
            webLinks.WebCategoryID = webCategoryID;
            webLinks.Name = name;
            webLinks.WebLink = webLink;
            webLinks.VisibleFlag = visibleFlag;
            webLinks.NeedAuthorizationFlag = needAuthorizationFlag;
            return webLinks;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 WebLinkID
        {
            get
            {
                return _WebLinkID;
            }
            set
            {
                if (_WebLinkID != value)
                {
                    OnWebLinkIDChanging(value);
                    ReportPropertyChanging("WebLinkID");
                    _WebLinkID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("WebLinkID");
                    OnWebLinkIDChanged();
                }
            }
        }
        private global::System.Int32 _WebLinkID;
        partial void OnWebLinkIDChanging(global::System.Int32 value);
        partial void OnWebLinkIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 WebCategoryID
        {
            get
            {
                return _WebCategoryID;
            }
            set
            {
                OnWebCategoryIDChanging(value);
                ReportPropertyChanging("WebCategoryID");
                _WebCategoryID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WebCategoryID");
                OnWebCategoryIDChanged();
            }
        }
        private global::System.Int32 _WebCategoryID;
        partial void OnWebCategoryIDChanging(global::System.Int32 value);
        partial void OnWebCategoryIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String WebLink
        {
            get
            {
                return _WebLink;
            }
            set
            {
                OnWebLinkChanging(value);
                ReportPropertyChanging("WebLink");
                _WebLink = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("WebLink");
                OnWebLinkChanged();
            }
        }
        private global::System.String _WebLink;
        partial void OnWebLinkChanging(global::System.String value);
        partial void OnWebLinkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean VisibleFlag
        {
            get
            {
                return _VisibleFlag;
            }
            set
            {
                OnVisibleFlagChanging(value);
                ReportPropertyChanging("VisibleFlag");
                _VisibleFlag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VisibleFlag");
                OnVisibleFlagChanged();
            }
        }
        private global::System.Boolean _VisibleFlag;
        partial void OnVisibleFlagChanging(global::System.Boolean value);
        partial void OnVisibleFlagChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean NeedAuthorizationFlag
        {
            get
            {
                return _NeedAuthorizationFlag;
            }
            set
            {
                OnNeedAuthorizationFlagChanging(value);
                ReportPropertyChanging("NeedAuthorizationFlag");
                _NeedAuthorizationFlag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NeedAuthorizationFlag");
                OnNeedAuthorizationFlagChanged();
            }
        }
        private global::System.Boolean _NeedAuthorizationFlag;
        partial void OnNeedAuthorizationFlagChanging(global::System.Boolean value);
        partial void OnNeedAuthorizationFlagChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SIAWebLinksModel", "FK_SIA_WebLinks_SIA_WebCategories", "SIA_WebCategories")]
        public WebCategories SIA_WebCategories
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<WebCategories>("SIAWebLinksModel.FK_SIA_WebLinks_SIA_WebCategories", "SIA_WebCategories").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<WebCategories>("SIAWebLinksModel.FK_SIA_WebLinks_SIA_WebCategories", "SIA_WebCategories").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<WebCategories> SIA_WebCategoriesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<WebCategories>("SIAWebLinksModel.FK_SIA_WebLinks_SIA_WebCategories", "SIA_WebCategories");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<WebCategories>("SIAWebLinksModel.FK_SIA_WebLinks_SIA_WebCategories", "SIA_WebCategories", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SIAWebLinksModel", "FK_Activity_ActivityLog_SIA_WebLinks", "Activity_ActivityLog")]
        public EntityCollection<ActivityLog> Activity_ActivityLog
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ActivityLog>("SIAWebLinksModel.FK_Activity_ActivityLog_SIA_WebLinks", "Activity_ActivityLog");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ActivityLog>("SIAWebLinksModel.FK_Activity_ActivityLog_SIA_WebLinks", "Activity_ActivityLog", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SIAWebLinksModel", "FK_Activity_ActivityLog_SIA_WebLinks1", "Activity_ActivityLog")]
        public EntityCollection<ActivityLog> Activity_ActivityLog1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ActivityLog>("SIAWebLinksModel.FK_Activity_ActivityLog_SIA_WebLinks1", "Activity_ActivityLog");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ActivityLog>("SIAWebLinksModel.FK_Activity_ActivityLog_SIA_WebLinks1", "Activity_ActivityLog", value);
                }
            }
        }

        #endregion

    }

    #endregion

    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="SIAWebLinksModel", Name="MyTopWebLinks_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class MyTopWebLinks_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MyTopWebLinks_Result object.
        /// </summary>
        /// <param name="topLinkPath">Initial value of the TopLinkPath property.</param>
        public static MyTopWebLinks_Result CreateMyTopWebLinks_Result(global::System.String topLinkPath)
        {
            MyTopWebLinks_Result myTopWebLinks_Result = new MyTopWebLinks_Result();
            myTopWebLinks_Result.TopLinkPath = topLinkPath;
            return myTopWebLinks_Result;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TopLink
        {
            get
            {
                return _TopLink;
            }
            set
            {
                OnTopLinkChanging(value);
                ReportPropertyChanging("TopLink");
                _TopLink = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TopLink");
                OnTopLinkChanged();
            }
        }
        private global::System.String _TopLink;
        partial void OnTopLinkChanging(global::System.String value);
        partial void OnTopLinkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TopLinkPath
        {
            get
            {
                return _TopLinkPath;
            }
            set
            {
                OnTopLinkPathChanging(value);
                ReportPropertyChanging("TopLinkPath");
                _TopLinkPath = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TopLinkPath");
                OnTopLinkPathChanged();
            }
        }
        private global::System.String _TopLinkPath;
        partial void OnTopLinkPathChanging(global::System.String value);
        partial void OnTopLinkPathChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="SIAWebLinksModel", Name="spGetAllSIAWebLinks_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class spGetAllSIAWebLinks_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new spGetAllSIAWebLinks_Result object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="webLink">Initial value of the WebLink property.</param>
        public static spGetAllSIAWebLinks_Result CreatespGetAllSIAWebLinks_Result(global::System.Int32 id, global::System.String name, global::System.String webLink)
        {
            spGetAllSIAWebLinks_Result spGetAllSIAWebLinks_Result = new spGetAllSIAWebLinks_Result();
            spGetAllSIAWebLinks_Result.ID = id;
            spGetAllSIAWebLinks_Result.Name = name;
            spGetAllSIAWebLinks_Result.WebLink = webLink;
            return spGetAllSIAWebLinks_Result;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                OnIDChanging(value);
                ReportPropertyChanging("ID");
                _ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID");
                OnIDChanged();
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String WebLink
        {
            get
            {
                return _WebLink;
            }
            set
            {
                OnWebLinkChanging(value);
                ReportPropertyChanging("WebLink");
                _WebLink = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("WebLink");
                OnWebLinkChanged();
            }
        }
        private global::System.String _WebLink;
        partial void OnWebLinkChanging(global::System.String value);
        partial void OnWebLinkChanged();

        #endregion

    }

    #endregion

    
}
