//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("PersonBasicModel", "FK_User_User_Person_Person", "Person_Person", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PersonnelBusinessLayer.Person_Person), "User_User", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(PersonnelBusinessLayer.User_User), true)]
[assembly: EdmRelationshipAttribute("PersonBasicModel", "User_JobTitleUser_User", "User_JobTitle", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PersonnelBusinessLayer.User_JobTitle), "User_User", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PersonnelBusinessLayer.User_User), true)]
[assembly: EdmRelationshipAttribute("PersonBasicModel", "FK_User_User_User_WorkStatus", "User_WorkStatus", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(PersonnelBusinessLayer.User_WorkStatus), "User_User", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PersonnelBusinessLayer.User_User), true)]

#endregion

namespace PersonnelBusinessLayer
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class PersonBasicContex : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new PersonBasicContex object using the connection string found in the 'PersonBasicContex' section of the application configuration file.
        /// </summary>
        public PersonBasicContex() : base("name=PersonBasicContex", "PersonBasicContex")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PersonBasicContex object.
        /// </summary>
        public PersonBasicContex(string connectionString) : base(connectionString, "PersonBasicContex")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PersonBasicContex object.
        /// </summary>
        public PersonBasicContex(EntityConnection connection) : base(connection, "PersonBasicContex")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Person_Person> Person_Person
        {
            get
            {
                if ((_Person_Person == null))
                {
                    _Person_Person = base.CreateObjectSet<Person_Person>("Person_Person");
                }
                return _Person_Person;
            }
        }
        private ObjectSet<Person_Person> _Person_Person;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User_User> User_User
        {
            get
            {
                if ((_User_User == null))
                {
                    _User_User = base.CreateObjectSet<User_User>("User_User");
                }
                return _User_User;
            }
        }
        private ObjectSet<User_User> _User_User;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User_JobTitle> User_JobTitle
        {
            get
            {
                if ((_User_JobTitle == null))
                {
                    _User_JobTitle = base.CreateObjectSet<User_JobTitle>("User_JobTitle");
                }
                return _User_JobTitle;
            }
        }
        private ObjectSet<User_JobTitle> _User_JobTitle;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User_WorkStatus> User_WorkStatus
        {
            get
            {
                if ((_User_WorkStatus == null))
                {
                    _User_WorkStatus = base.CreateObjectSet<User_WorkStatus>("User_WorkStatus");
                }
                return _User_WorkStatus;
            }
        }
        private ObjectSet<User_WorkStatus> _User_WorkStatus;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Person_Person EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPerson_Person(Person_Person person_Person)
        {
            base.AddObject("Person_Person", person_Person);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the User_User EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUser_User(User_User user_User)
        {
            base.AddObject("User_User", user_User);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the User_JobTitle EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUser_JobTitle(User_JobTitle user_JobTitle)
        {
            base.AddObject("User_JobTitle", user_JobTitle);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the User_WorkStatus EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUser_WorkStatus(User_WorkStatus user_WorkStatus)
        {
            base.AddObject("User_WorkStatus", user_WorkStatus);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PersonBasicModel", Name="Person_Person")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Person_Person : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Person_Person object.
        /// </summary>
        /// <param name="appEntityID">Initial value of the AppEntityID property.</param>
        public static Person_Person CreatePerson_Person(global::System.Int32 appEntityID)
        {
            Person_Person person_Person = new Person_Person();
            person_Person.AppEntityID = appEntityID;
            return person_Person;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AppEntityID
        {
            get
            {
                return _AppEntityID;
            }
            set
            {
                if (_AppEntityID != value)
                {
                    OnAppEntityIDChanging(value);
                    ReportPropertyChanging("AppEntityID");
                    _AppEntityID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AppEntityID");
                    OnAppEntityIDChanged();
                }
            }
        }
        private global::System.Int32 _AppEntityID;
        partial void OnAppEntityIDChanging(global::System.Int32 value);
        partial void OnAppEntityIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PersonTypeID
        {
            get
            {
                return _PersonTypeID;
            }
            set
            {
                OnPersonTypeIDChanging(value);
                ReportPropertyChanging("PersonTypeID");
                _PersonTypeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PersonTypeID");
                OnPersonTypeIDChanged();
            }
        }
        private Nullable<global::System.Int32> _PersonTypeID;
        partial void OnPersonTypeIDChanging(Nullable<global::System.Int32> value);
        partial void OnPersonTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MiddleName
        {
            get
            {
                return _MiddleName;
            }
            set
            {
                OnMiddleNameChanging(value);
                ReportPropertyChanging("MiddleName");
                _MiddleName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MiddleName");
                OnMiddleNameChanged();
            }
        }
        private global::System.String _MiddleName;
        partial void OnMiddleNameChanging(global::System.String value);
        partial void OnMiddleNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Suffix
        {
            get
            {
                return _Suffix;
            }
            set
            {
                OnSuffixChanging(value);
                ReportPropertyChanging("Suffix");
                _Suffix = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Suffix");
                OnSuffixChanged();
            }
        }
        private global::System.String _Suffix;
        partial void OnSuffixChanging(global::System.String value);
        partial void OnSuffixChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> rowguid
        {
            get
            {
                return _rowguid;
            }
            set
            {
                OnrowguidChanging(value);
                ReportPropertyChanging("rowguid");
                _rowguid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("rowguid");
                OnrowguidChanged();
            }
        }
        private Nullable<global::System.Guid> _rowguid;
        partial void OnrowguidChanging(Nullable<global::System.Guid> value);
        partial void OnrowguidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return _ModifiedDate;
            }
            set
            {
                OnModifiedDateChanging(value);
                ReportPropertyChanging("ModifiedDate");
                _ModifiedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedDate");
                OnModifiedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModifiedDate;
        partial void OnModifiedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnModifiedDateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PersonBasicModel", "FK_User_User_Person_Person", "User_User")]
        public User_User User_User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User_User>("PersonBasicModel.FK_User_User_Person_Person", "User_User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User_User>("PersonBasicModel.FK_User_User_Person_Person", "User_User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User_User> User_UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User_User>("PersonBasicModel.FK_User_User_Person_Person", "User_User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User_User>("PersonBasicModel.FK_User_User_Person_Person", "User_User", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PersonBasicModel", Name="User_JobTitle")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User_JobTitle : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User_JobTitle object.
        /// </summary>
        /// <param name="jobTitleID">Initial value of the JobTitleID property.</param>
        public static User_JobTitle CreateUser_JobTitle(global::System.Int32 jobTitleID)
        {
            User_JobTitle user_JobTitle = new User_JobTitle();
            user_JobTitle.JobTitleID = jobTitleID;
            return user_JobTitle;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 JobTitleID
        {
            get
            {
                return _JobTitleID;
            }
            set
            {
                if (_JobTitleID != value)
                {
                    OnJobTitleIDChanging(value);
                    ReportPropertyChanging("JobTitleID");
                    _JobTitleID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("JobTitleID");
                    OnJobTitleIDChanged();
                }
            }
        }
        private global::System.Int32 _JobTitleID;
        partial void OnJobTitleIDChanging(global::System.Int32 value);
        partial void OnJobTitleIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NameCode
        {
            get
            {
                return _NameCode;
            }
            set
            {
                OnNameCodeChanging(value);
                ReportPropertyChanging("NameCode");
                _NameCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NameCode");
                OnNameCodeChanged();
            }
        }
        private global::System.String _NameCode;
        partial void OnNameCodeChanging(global::System.String value);
        partial void OnNameCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> jtRanking
        {
            get
            {
                return _jtRanking;
            }
            set
            {
                OnjtRankingChanging(value);
                ReportPropertyChanging("jtRanking");
                _jtRanking = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("jtRanking");
                OnjtRankingChanged();
            }
        }
        private Nullable<global::System.Int32> _jtRanking;
        partial void OnjtRankingChanging(Nullable<global::System.Int32> value);
        partial void OnjtRankingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return _ModifiedDate;
            }
            set
            {
                OnModifiedDateChanging(value);
                ReportPropertyChanging("ModifiedDate");
                _ModifiedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedDate");
                OnModifiedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModifiedDate;
        partial void OnModifiedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnModifiedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> VisibleFlag
        {
            get
            {
                return _VisibleFlag;
            }
            set
            {
                OnVisibleFlagChanging(value);
                ReportPropertyChanging("VisibleFlag");
                _VisibleFlag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VisibleFlag");
                OnVisibleFlagChanged();
            }
        }
        private Nullable<global::System.Boolean> _VisibleFlag;
        partial void OnVisibleFlagChanging(Nullable<global::System.Boolean> value);
        partial void OnVisibleFlagChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PAJobTitleID
        {
            get
            {
                return _PAJobTitleID;
            }
            set
            {
                OnPAJobTitleIDChanging(value);
                ReportPropertyChanging("PAJobTitleID");
                _PAJobTitleID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PAJobTitleID");
                OnPAJobTitleIDChanged();
            }
        }
        private Nullable<global::System.Int32> _PAJobTitleID;
        partial void OnPAJobTitleIDChanging(Nullable<global::System.Int32> value);
        partial void OnPAJobTitleIDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PersonBasicModel", "User_JobTitleUser_User", "User_User")]
        public EntityCollection<User_User> User_User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<User_User>("PersonBasicModel.User_JobTitleUser_User", "User_User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<User_User>("PersonBasicModel.User_JobTitleUser_User", "User_User", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PersonBasicModel", Name="User_User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User_User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User_User object.
        /// </summary>
        /// <param name="appEntityID">Initial value of the AppEntityID property.</param>
        /// <param name="jobTitleID">Initial value of the JobTitleID property.</param>
        /// <param name="hireDate">Initial value of the HireDate property.</param>
        public static User_User CreateUser_User(global::System.Int32 appEntityID, global::System.Int32 jobTitleID, global::System.DateTime hireDate)
        {
            User_User user_User = new User_User();
            user_User.AppEntityID = appEntityID;
            user_User.JobTitleID = jobTitleID;
            user_User.HireDate = hireDate;
            return user_User;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AppEntityID
        {
            get
            {
                return _AppEntityID;
            }
            set
            {
                if (_AppEntityID != value)
                {
                    OnAppEntityIDChanging(value);
                    ReportPropertyChanging("AppEntityID");
                    _AppEntityID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AppEntityID");
                    OnAppEntityIDChanged();
                }
            }
        }
        private global::System.Int32 _AppEntityID;
        partial void OnAppEntityIDChanging(global::System.Int32 value);
        partial void OnAppEntityIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PIN
        {
            get
            {
                return _PIN;
            }
            set
            {
                OnPINChanging(value);
                ReportPropertyChanging("PIN");
                _PIN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PIN");
                OnPINChanged();
            }
        }
        private global::System.String _PIN;
        partial void OnPINChanging(global::System.String value);
        partial void OnPINChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SAP
        {
            get
            {
                return _SAP;
            }
            set
            {
                OnSAPChanging(value);
                ReportPropertyChanging("SAP");
                _SAP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SAP");
                OnSAPChanged();
            }
        }
        private global::System.String _SAP;
        partial void OnSAPChanging(global::System.String value);
        partial void OnSAPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CADID
        {
            get
            {
                return _CADID;
            }
            set
            {
                OnCADIDChanging(value);
                ReportPropertyChanging("CADID");
                _CADID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CADID");
                OnCADIDChanged();
            }
        }
        private Nullable<global::System.Int32> _CADID;
        partial void OnCADIDChanging(Nullable<global::System.Int32> value);
        partial void OnCADIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Badge
        {
            get
            {
                return _Badge;
            }
            set
            {
                OnBadgeChanging(value);
                ReportPropertyChanging("Badge");
                _Badge = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Badge");
                OnBadgeChanged();
            }
        }
        private global::System.String _Badge;
        partial void OnBadgeChanging(global::System.String value);
        partial void OnBadgeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 JobTitleID
        {
            get
            {
                return _JobTitleID;
            }
            set
            {
                OnJobTitleIDChanging(value);
                ReportPropertyChanging("JobTitleID");
                _JobTitleID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("JobTitleID");
                OnJobTitleIDChanged();
            }
        }
        private global::System.Int32 _JobTitleID;
        partial void OnJobTitleIDChanging(global::System.Int32 value);
        partial void OnJobTitleIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> OfficeID
        {
            get
            {
                return _OfficeID;
            }
            set
            {
                OnOfficeIDChanging(value);
                ReportPropertyChanging("OfficeID");
                _OfficeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OfficeID");
                OnOfficeIDChanged();
            }
        }
        private Nullable<global::System.Int32> _OfficeID;
        partial void OnOfficeIDChanging(Nullable<global::System.Int32> value);
        partial void OnOfficeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SectionID
        {
            get
            {
                return _SectionID;
            }
            set
            {
                OnSectionIDChanging(value);
                ReportPropertyChanging("SectionID");
                _SectionID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SectionID");
                OnSectionIDChanged();
            }
        }
        private Nullable<global::System.Int32> _SectionID;
        partial void OnSectionIDChanging(Nullable<global::System.Int32> value);
        partial void OnSectionIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RDID
        {
            get
            {
                return _RDID;
            }
            set
            {
                OnRDIDChanging(value);
                ReportPropertyChanging("RDID");
                _RDID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RDID");
                OnRDIDChanged();
            }
        }
        private Nullable<global::System.Int32> _RDID;
        partial void OnRDIDChanging(Nullable<global::System.Int32> value);
        partial void OnRDIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ClassificationID
        {
            get
            {
                return _ClassificationID;
            }
            set
            {
                OnClassificationIDChanging(value);
                ReportPropertyChanging("ClassificationID");
                _ClassificationID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClassificationID");
                OnClassificationIDChanged();
            }
        }
        private Nullable<global::System.Int32> _ClassificationID;
        partial void OnClassificationIDChanging(Nullable<global::System.Int32> value);
        partial void OnClassificationIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ShiftID
        {
            get
            {
                return _ShiftID;
            }
            set
            {
                OnShiftIDChanging(value);
                ReportPropertyChanging("ShiftID");
                _ShiftID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ShiftID");
                OnShiftIDChanged();
            }
        }
        private Nullable<global::System.Int32> _ShiftID;
        partial void OnShiftIDChanging(Nullable<global::System.Int32> value);
        partial void OnShiftIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> WorkStatusID
        {
            get
            {
                return _WorkStatusID;
            }
            set
            {
                OnWorkStatusIDChanging(value);
                ReportPropertyChanging("WorkStatusID");
                _WorkStatusID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WorkStatusID");
                OnWorkStatusIDChanged();
            }
        }
        private Nullable<global::System.Int32> _WorkStatusID;
        partial void OnWorkStatusIDChanging(Nullable<global::System.Int32> value);
        partial void OnWorkStatusIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DOB
        {
            get
            {
                return _DOB;
            }
            set
            {
                OnDOBChanging(value);
                ReportPropertyChanging("DOB");
                _DOB = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DOB");
                OnDOBChanged();
            }
        }
        private Nullable<global::System.DateTime> _DOB;
        partial void OnDOBChanging(Nullable<global::System.DateTime> value);
        partial void OnDOBChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Gender
        {
            get
            {
                return _Gender;
            }
            set
            {
                OnGenderChanging(value);
                ReportPropertyChanging("Gender");
                _Gender = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Gender");
                OnGenderChanged();
            }
        }
        private global::System.String _Gender;
        partial void OnGenderChanging(global::System.String value);
        partial void OnGenderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ethnicty
        {
            get
            {
                return _Ethnicty;
            }
            set
            {
                OnEthnictyChanging(value);
                ReportPropertyChanging("Ethnicty");
                _Ethnicty = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ethnicty");
                OnEthnictyChanged();
            }
        }
        private global::System.String _Ethnicty;
        partial void OnEthnictyChanging(global::System.String value);
        partial void OnEthnictyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MaritalStatus
        {
            get
            {
                return _MaritalStatus;
            }
            set
            {
                OnMaritalStatusChanging(value);
                ReportPropertyChanging("MaritalStatus");
                _MaritalStatus = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MaritalStatus");
                OnMaritalStatusChanged();
            }
        }
        private global::System.String _MaritalStatus;
        partial void OnMaritalStatusChanging(global::System.String value);
        partial void OnMaritalStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime HireDate
        {
            get
            {
                return _HireDate;
            }
            set
            {
                OnHireDateChanging(value);
                ReportPropertyChanging("HireDate");
                _HireDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HireDate");
                OnHireDateChanged();
            }
        }
        private global::System.DateTime _HireDate;
        partial void OnHireDateChanging(global::System.DateTime value);
        partial void OnHireDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> rowguid
        {
            get
            {
                return _rowguid;
            }
            set
            {
                OnrowguidChanging(value);
                ReportPropertyChanging("rowguid");
                _rowguid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("rowguid");
                OnrowguidChanged();
            }
        }
        private Nullable<global::System.Guid> _rowguid;
        partial void OnrowguidChanging(Nullable<global::System.Guid> value);
        partial void OnrowguidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> WorksheetVisibleFlag
        {
            get
            {
                return _WorksheetVisibleFlag;
            }
            set
            {
                OnWorksheetVisibleFlagChanging(value);
                ReportPropertyChanging("WorksheetVisibleFlag");
                _WorksheetVisibleFlag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WorksheetVisibleFlag");
                OnWorksheetVisibleFlagChanged();
            }
        }
        private Nullable<global::System.Boolean> _WorksheetVisibleFlag;
        partial void OnWorksheetVisibleFlagChanging(Nullable<global::System.Boolean> value);
        partial void OnWorksheetVisibleFlagChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return _ModifiedDate;
            }
            set
            {
                OnModifiedDateChanging(value);
                ReportPropertyChanging("ModifiedDate");
                _ModifiedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedDate");
                OnModifiedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModifiedDate;
        partial void OnModifiedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnModifiedDateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PersonBasicModel", "FK_User_User_Person_Person", "Person_Person")]
        public Person_Person Person_Person
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Person_Person>("PersonBasicModel.FK_User_User_Person_Person", "Person_Person").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Person_Person>("PersonBasicModel.FK_User_User_Person_Person", "Person_Person").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Person_Person> Person_PersonReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Person_Person>("PersonBasicModel.FK_User_User_Person_Person", "Person_Person");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Person_Person>("PersonBasicModel.FK_User_User_Person_Person", "Person_Person", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PersonBasicModel", "User_JobTitleUser_User", "User_JobTitle")]
        public User_JobTitle User_JobTitle
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User_JobTitle>("PersonBasicModel.User_JobTitleUser_User", "User_JobTitle").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User_JobTitle>("PersonBasicModel.User_JobTitleUser_User", "User_JobTitle").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User_JobTitle> User_JobTitleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User_JobTitle>("PersonBasicModel.User_JobTitleUser_User", "User_JobTitle");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User_JobTitle>("PersonBasicModel.User_JobTitleUser_User", "User_JobTitle", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PersonBasicModel", "FK_User_User_User_WorkStatus", "User_WorkStatus")]
        public User_WorkStatus User_WorkStatus
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User_WorkStatus>("PersonBasicModel.FK_User_User_User_WorkStatus", "User_WorkStatus").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User_WorkStatus>("PersonBasicModel.FK_User_User_User_WorkStatus", "User_WorkStatus").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User_WorkStatus> User_WorkStatusReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User_WorkStatus>("PersonBasicModel.FK_User_User_User_WorkStatus", "User_WorkStatus");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User_WorkStatus>("PersonBasicModel.FK_User_User_User_WorkStatus", "User_WorkStatus", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PersonBasicModel", Name="User_WorkStatus")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User_WorkStatus : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User_WorkStatus object.
        /// </summary>
        /// <param name="workStatusID">Initial value of the WorkStatusID property.</param>
        public static User_WorkStatus CreateUser_WorkStatus(global::System.Int32 workStatusID)
        {
            User_WorkStatus user_WorkStatus = new User_WorkStatus();
            user_WorkStatus.WorkStatusID = workStatusID;
            return user_WorkStatus;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 WorkStatusID
        {
            get
            {
                return _WorkStatusID;
            }
            set
            {
                if (_WorkStatusID != value)
                {
                    OnWorkStatusIDChanging(value);
                    ReportPropertyChanging("WorkStatusID");
                    _WorkStatusID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("WorkStatusID");
                    OnWorkStatusIDChanged();
                }
            }
        }
        private global::System.Int32 _WorkStatusID;
        partial void OnWorkStatusIDChanging(global::System.Int32 value);
        partial void OnWorkStatusIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NameCode
        {
            get
            {
                return _NameCode;
            }
            set
            {
                OnNameCodeChanging(value);
                ReportPropertyChanging("NameCode");
                _NameCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NameCode");
                OnNameCodeChanged();
            }
        }
        private global::System.String _NameCode;
        partial void OnNameCodeChanging(global::System.String value);
        partial void OnNameCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Ranking
        {
            get
            {
                return _Ranking;
            }
            set
            {
                OnRankingChanging(value);
                ReportPropertyChanging("Ranking");
                _Ranking = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ranking");
                OnRankingChanged();
            }
        }
        private Nullable<global::System.Int32> _Ranking;
        partial void OnRankingChanging(Nullable<global::System.Int32> value);
        partial void OnRankingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return _ModifiedDate;
            }
            set
            {
                OnModifiedDateChanging(value);
                ReportPropertyChanging("ModifiedDate");
                _ModifiedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedDate");
                OnModifiedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModifiedDate;
        partial void OnModifiedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnModifiedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> VisibleFlag
        {
            get
            {
                return _VisibleFlag;
            }
            set
            {
                OnVisibleFlagChanging(value);
                ReportPropertyChanging("VisibleFlag");
                _VisibleFlag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VisibleFlag");
                OnVisibleFlagChanged();
            }
        }
        private Nullable<global::System.Boolean> _VisibleFlag;
        partial void OnVisibleFlagChanging(Nullable<global::System.Boolean> value);
        partial void OnVisibleFlagChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PAWorkStatusID
        {
            get
            {
                return _PAWorkStatusID;
            }
            set
            {
                OnPAWorkStatusIDChanging(value);
                ReportPropertyChanging("PAWorkStatusID");
                _PAWorkStatusID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PAWorkStatusID");
                OnPAWorkStatusIDChanged();
            }
        }
        private Nullable<global::System.Int32> _PAWorkStatusID;
        partial void OnPAWorkStatusIDChanging(Nullable<global::System.Int32> value);
        partial void OnPAWorkStatusIDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PersonBasicModel", "FK_User_User_User_WorkStatus", "User_User")]
        public EntityCollection<User_User> User_User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<User_User>("PersonBasicModel.FK_User_User_User_WorkStatus", "User_User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<User_User>("PersonBasicModel.FK_User_User_User_WorkStatus", "User_User", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
