//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("IECAModel", "AppEntityAuditHistrory", "AppEntity", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(IECAWeb.Models.AppEntity), "AuditHistrory", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(IECAWeb.Models.AuditHistrory), true)]
[assembly: EdmRelationshipAttribute("IECAModel", "OfficerAppEntity", "Officer", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(IECAWeb.Models.Officer), "AppEntity", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(IECAWeb.Models.AppEntity), true)]
[assembly: EdmRelationshipAttribute("IECAModel", "FK_User_User_Person_Person", "Officer", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(IECAWeb.Models.Officer), "User_User", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(IECAWeb.Models.User_User), true)]
[assembly: EdmRelationshipAttribute("IECAModel", "Grant_vActivityApproverAuditHistrory", "Grant_vActivityApprover", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(IECAWeb.Models.Auditor), "AuditHistrory", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(IECAWeb.Models.AuditHistrory), true)]

#endregion

namespace IECAWeb.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AuditEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AuditEntities object using the connection string found in the 'AuditEntities' section of the application configuration file.
        /// </summary>
        public AuditEntities() : base("name=AuditEntities", "AuditEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AuditEntities object.
        /// </summary>
        public AuditEntities(string connectionString) : base(connectionString, "AuditEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AuditEntities object.
        /// </summary>
        public AuditEntities(EntityConnection connection) : base(connection, "AuditEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AuditHistrory> AuditHistrories
        {
            get
            {
                if ((_AuditHistrories == null))
                {
                    _AuditHistrories = base.CreateObjectSet<AuditHistrory>("AuditHistrories");
                }
                return _AuditHistrories;
            }
        }
        private ObjectSet<AuditHistrory> _AuditHistrories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AppEntity> AppEntities
        {
            get
            {
                if ((_AppEntities == null))
                {
                    _AppEntities = base.CreateObjectSet<AppEntity>("AppEntities");
                }
                return _AppEntities;
            }
        }
        private ObjectSet<AppEntity> _AppEntities;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Officer> Officers
        {
            get
            {
                if ((_Officers == null))
                {
                    _Officers = base.CreateObjectSet<Officer>("Officers");
                }
                return _Officers;
            }
        }
        private ObjectSet<Officer> _Officers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User_User> User_User
        {
            get
            {
                if ((_User_User == null))
                {
                    _User_User = base.CreateObjectSet<User_User>("User_User");
                }
                return _User_User;
            }
        }
        private ObjectSet<User_User> _User_User;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Auditor> Auditors
        {
            get
            {
                if ((_Auditors == null))
                {
                    _Auditors = base.CreateObjectSet<Auditor>("Auditors");
                }
                return _Auditors;
            }
        }
        private ObjectSet<Auditor> _Auditors;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AuditHistrories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAuditHistrories(AuditHistrory auditHistrory)
        {
            base.AddObject("AuditHistrories", auditHistrory);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AppEntities EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAppEntities(AppEntity appEntity)
        {
            base.AddObject("AppEntities", appEntity);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Officers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOfficers(Officer officer)
        {
            base.AddObject("Officers", officer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the User_User EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUser_User(User_User user_User)
        {
            base.AddObject("User_User", user_User);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Auditors EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAuditors(Auditor auditor)
        {
            base.AddObject("Auditors", auditor);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IECAModel", Name="AppEntity")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AppEntity : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AppEntity object.
        /// </summary>
        /// <param name="appEntityID">Initial value of the AppEntityID property.</param>
        /// <param name="rowguid">Initial value of the rowguid property.</param>
        public static AppEntity CreateAppEntity(global::System.Int32 appEntityID, global::System.Guid rowguid)
        {
            AppEntity appEntity = new AppEntity();
            appEntity.AppEntityID = appEntityID;
            appEntity.rowguid = rowguid;
            return appEntity;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AppEntityID
        {
            get
            {
                return _AppEntityID;
            }
            set
            {
                if (_AppEntityID != value)
                {
                    OnAppEntityIDChanging(value);
                    ReportPropertyChanging("AppEntityID");
                    _AppEntityID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AppEntityID");
                    OnAppEntityIDChanged();
                }
            }
        }
        private global::System.Int32 _AppEntityID;
        partial void OnAppEntityIDChanging(global::System.Int32 value);
        partial void OnAppEntityIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid rowguid
        {
            get
            {
                return _rowguid;
            }
            set
            {
                OnrowguidChanging(value);
                ReportPropertyChanging("rowguid");
                _rowguid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("rowguid");
                OnrowguidChanged();
            }
        }
        private global::System.Guid _rowguid;
        partial void OnrowguidChanging(global::System.Guid value);
        partial void OnrowguidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return _ModifiedDate;
            }
            set
            {
                OnModifiedDateChanging(value);
                ReportPropertyChanging("ModifiedDate");
                _ModifiedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedDate");
                OnModifiedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModifiedDate;
        partial void OnModifiedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnModifiedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PAUserID
        {
            get
            {
                return _PAUserID;
            }
            set
            {
                OnPAUserIDChanging(value);
                ReportPropertyChanging("PAUserID");
                _PAUserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PAUserID");
                OnPAUserIDChanged();
            }
        }
        private Nullable<global::System.Int32> _PAUserID;
        partial void OnPAUserIDChanging(Nullable<global::System.Int32> value);
        partial void OnPAUserIDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("IECAModel", "AppEntityAuditHistrory", "AuditHistrory")]
        public EntityCollection<AuditHistrory> AuditHistrories
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<AuditHistrory>("IECAModel.AppEntityAuditHistrory", "AuditHistrory");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<AuditHistrory>("IECAModel.AppEntityAuditHistrory", "AuditHistrory", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("IECAModel", "OfficerAppEntity", "Officer")]
        public Officer Officer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Officer>("IECAModel.OfficerAppEntity", "Officer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Officer>("IECAModel.OfficerAppEntity", "Officer").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Officer> OfficerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Officer>("IECAModel.OfficerAppEntity", "Officer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Officer>("IECAModel.OfficerAppEntity", "Officer", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IECAModel", Name="AuditHistrory")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AuditHistrory : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AuditHistrory object.
        /// </summary>
        /// <param name="iECAID">Initial value of the IECAID property.</param>
        /// <param name="appEntityID">Initial value of the AppEntityID property.</param>
        /// <param name="officeID">Initial value of the OfficeID property.</param>
        public static AuditHistrory CreateAuditHistrory(global::System.Int32 iECAID, global::System.Int32 appEntityID, global::System.Int32 officeID)
        {
            AuditHistrory auditHistrory = new AuditHistrory();
            auditHistrory.IECAID = iECAID;
            auditHistrory.AppEntityID = appEntityID;
            auditHistrory.OfficeID = officeID;
            return auditHistrory;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IECAID
        {
            get
            {
                return _IECAID;
            }
            set
            {
                if (_IECAID != value)
                {
                    OnIECAIDChanging(value);
                    ReportPropertyChanging("IECAID");
                    _IECAID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IECAID");
                    OnIECAIDChanged();
                }
            }
        }
        private global::System.Int32 _IECAID;
        partial void OnIECAIDChanging(global::System.Int32 value);
        partial void OnIECAIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AppEntityID
        {
            get
            {
                return _AppEntityID;
            }
            set
            {
                OnAppEntityIDChanging(value);
                ReportPropertyChanging("AppEntityID");
                _AppEntityID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AppEntityID");
                OnAppEntityIDChanged();
            }
        }
        private global::System.Int32 _AppEntityID;
        partial void OnAppEntityIDChanging(global::System.Int32 value);
        partial void OnAppEntityIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OfficeID
        {
            get
            {
                return _OfficeID;
            }
            set
            {
                OnOfficeIDChanging(value);
                ReportPropertyChanging("OfficeID");
                _OfficeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OfficeID");
                OnOfficeIDChanged();
            }
        }
        private global::System.Int32 _OfficeID;
        partial void OnOfficeIDChanging(global::System.Int32 value);
        partial void OnOfficeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> CaseAuditFlag
        {
            get
            {
                return _CaseAuditFlag;
            }
            set
            {
                OnCaseAuditFlagChanging(value);
                ReportPropertyChanging("CaseAuditFlag");
                _CaseAuditFlag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CaseAuditFlag");
                OnCaseAuditFlagChanged();
            }
        }
        private Nullable<global::System.Boolean> _CaseAuditFlag;
        partial void OnCaseAuditFlagChanging(Nullable<global::System.Boolean> value);
        partial void OnCaseAuditFlagChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AuditNotes
        {
            get
            {
                return _AuditNotes;
            }
            set
            {
                OnAuditNotesChanging(value);
                ReportPropertyChanging("AuditNotes");
                _AuditNotes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AuditNotes");
                OnAuditNotesChanged();
            }
        }
        private global::System.String _AuditNotes;
        partial void OnAuditNotesChanging(global::System.String value);
        partial void OnAuditNotesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> AuditDate
        {
            get
            {
                return _AuditDate;
            }
            set
            {
                OnAuditDateChanging(value);
                ReportPropertyChanging("AuditDate");
                _AuditDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AuditDate");
                OnAuditDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _AuditDate;
        partial void OnAuditDateChanging(Nullable<global::System.DateTime> value);
        partial void OnAuditDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AuditByID
        {
            get
            {
                return _AuditByID;
            }
            set
            {
                OnAuditByIDChanging(value);
                ReportPropertyChanging("AuditByID");
                _AuditByID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AuditByID");
                OnAuditByIDChanged();
            }
        }
        private Nullable<global::System.Int32> _AuditByID;
        partial void OnAuditByIDChanging(Nullable<global::System.Int32> value);
        partial void OnAuditByIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> InsertDate
        {
            get
            {
                return _InsertDate;
            }
            set
            {
                OnInsertDateChanging(value);
                ReportPropertyChanging("InsertDate");
                _InsertDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InsertDate");
                OnInsertDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _InsertDate;
        partial void OnInsertDateChanging(Nullable<global::System.DateTime> value);
        partial void OnInsertDateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("IECAModel", "AppEntityAuditHistrory", "AppEntity")]
        public AppEntity AppEntity
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AppEntity>("IECAModel.AppEntityAuditHistrory", "AppEntity").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AppEntity>("IECAModel.AppEntityAuditHistrory", "AppEntity").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<AppEntity> AppEntityReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AppEntity>("IECAModel.AppEntityAuditHistrory", "AppEntity");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<AppEntity>("IECAModel.AppEntityAuditHistrory", "AppEntity", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("IECAModel", "Grant_vActivityApproverAuditHistrory", "Grant_vActivityApprover")]
        public Auditor Grant_vActivityApprover
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Auditor>("IECAModel.Grant_vActivityApproverAuditHistrory", "Grant_vActivityApprover").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Auditor>("IECAModel.Grant_vActivityApproverAuditHistrory", "Grant_vActivityApprover").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Auditor> Grant_vActivityApproverReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Auditor>("IECAModel.Grant_vActivityApproverAuditHistrory", "Grant_vActivityApprover");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Auditor>("IECAModel.Grant_vActivityApproverAuditHistrory", "Grant_vActivityApprover", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IECAModel", Name="Auditor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Auditor : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Auditor object.
        /// </summary>
        /// <param name="appEntityID">Initial value of the AppEntityID property.</param>
        public static Auditor CreateAuditor(global::System.Int32 appEntityID)
        {
            Auditor auditor = new Auditor();
            auditor.AppEntityID = appEntityID;
            return auditor;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AppEntityID
        {
            get
            {
                return _AppEntityID;
            }
            set
            {
                if (_AppEntityID != value)
                {
                    OnAppEntityIDChanging(value);
                    ReportPropertyChanging("AppEntityID");
                    _AppEntityID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AppEntityID");
                    OnAppEntityIDChanged();
                }
            }
        }
        private global::System.Int32 _AppEntityID;
        partial void OnAppEntityIDChanging(global::System.Int32 value);
        partial void OnAppEntityIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ApproveBy
        {
            get
            {
                return _ApproveBy;
            }
            set
            {
                OnApproveByChanging(value);
                ReportPropertyChanging("ApproveBy");
                _ApproveBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ApproveBy");
                OnApproveByChanged();
            }
        }
        private global::System.String _ApproveBy;
        partial void OnApproveByChanging(global::System.String value);
        partial void OnApproveByChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("IECAModel", "Grant_vActivityApproverAuditHistrory", "AuditHistrory")]
        public EntityCollection<AuditHistrory> AuditHistrories
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<AuditHistrory>("IECAModel.Grant_vActivityApproverAuditHistrory", "AuditHistrory");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<AuditHistrory>("IECAModel.Grant_vActivityApproverAuditHistrory", "AuditHistrory", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IECAModel", Name="Officer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Officer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Officer object.
        /// </summary>
        /// <param name="appEntityID">Initial value of the AppEntityID property.</param>
        public static Officer CreateOfficer(global::System.Int32 appEntityID)
        {
            Officer officer = new Officer();
            officer.AppEntityID = appEntityID;
            return officer;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AppEntityID
        {
            get
            {
                return _AppEntityID;
            }
            set
            {
                if (_AppEntityID != value)
                {
                    OnAppEntityIDChanging(value);
                    ReportPropertyChanging("AppEntityID");
                    _AppEntityID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AppEntityID");
                    OnAppEntityIDChanged();
                }
            }
        }
        private global::System.Int32 _AppEntityID;
        partial void OnAppEntityIDChanging(global::System.Int32 value);
        partial void OnAppEntityIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PersonTypeID
        {
            get
            {
                return _PersonTypeID;
            }
            set
            {
                OnPersonTypeIDChanging(value);
                ReportPropertyChanging("PersonTypeID");
                _PersonTypeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PersonTypeID");
                OnPersonTypeIDChanged();
            }
        }
        private Nullable<global::System.Int32> _PersonTypeID;
        partial void OnPersonTypeIDChanging(Nullable<global::System.Int32> value);
        partial void OnPersonTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MiddleName
        {
            get
            {
                return _MiddleName;
            }
            set
            {
                OnMiddleNameChanging(value);
                ReportPropertyChanging("MiddleName");
                _MiddleName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MiddleName");
                OnMiddleNameChanged();
            }
        }
        private global::System.String _MiddleName;
        partial void OnMiddleNameChanging(global::System.String value);
        partial void OnMiddleNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Suffix
        {
            get
            {
                return _Suffix;
            }
            set
            {
                OnSuffixChanging(value);
                ReportPropertyChanging("Suffix");
                _Suffix = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Suffix");
                OnSuffixChanged();
            }
        }
        private global::System.String _Suffix;
        partial void OnSuffixChanging(global::System.String value);
        partial void OnSuffixChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> rowguid
        {
            get
            {
                return _rowguid;
            }
            set
            {
                OnrowguidChanging(value);
                ReportPropertyChanging("rowguid");
                _rowguid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("rowguid");
                OnrowguidChanged();
            }
        }
        private Nullable<global::System.Guid> _rowguid;
        partial void OnrowguidChanging(Nullable<global::System.Guid> value);
        partial void OnrowguidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return _ModifiedDate;
            }
            set
            {
                OnModifiedDateChanging(value);
                ReportPropertyChanging("ModifiedDate");
                _ModifiedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedDate");
                OnModifiedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModifiedDate;
        partial void OnModifiedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnModifiedDateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("IECAModel", "OfficerAppEntity", "AppEntity")]
        public AppEntity AppEntity
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AppEntity>("IECAModel.OfficerAppEntity", "AppEntity").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AppEntity>("IECAModel.OfficerAppEntity", "AppEntity").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<AppEntity> AppEntityReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AppEntity>("IECAModel.OfficerAppEntity", "AppEntity");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<AppEntity>("IECAModel.OfficerAppEntity", "AppEntity", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("IECAModel", "FK_User_User_Person_Person", "User_User")]
        public User_User User_User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User_User>("IECAModel.FK_User_User_Person_Person", "User_User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User_User>("IECAModel.FK_User_User_Person_Person", "User_User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User_User> User_UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User_User>("IECAModel.FK_User_User_Person_Person", "User_User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User_User>("IECAModel.FK_User_User_Person_Person", "User_User", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IECAModel", Name="User_User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User_User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User_User object.
        /// </summary>
        /// <param name="appEntityID">Initial value of the AppEntityID property.</param>
        public static User_User CreateUser_User(global::System.Int32 appEntityID)
        {
            User_User user_User = new User_User();
            user_User.AppEntityID = appEntityID;
            return user_User;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AppEntityID
        {
            get
            {
                return _AppEntityID;
            }
            set
            {
                if (_AppEntityID != value)
                {
                    OnAppEntityIDChanging(value);
                    ReportPropertyChanging("AppEntityID");
                    _AppEntityID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AppEntityID");
                    OnAppEntityIDChanged();
                }
            }
        }
        private global::System.Int32 _AppEntityID;
        partial void OnAppEntityIDChanging(global::System.Int32 value);
        partial void OnAppEntityIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PIN
        {
            get
            {
                return _PIN;
            }
            set
            {
                OnPINChanging(value);
                ReportPropertyChanging("PIN");
                _PIN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PIN");
                OnPINChanged();
            }
        }
        private global::System.String _PIN;
        partial void OnPINChanging(global::System.String value);
        partial void OnPINChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SAP
        {
            get
            {
                return _SAP;
            }
            set
            {
                OnSAPChanging(value);
                ReportPropertyChanging("SAP");
                _SAP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SAP");
                OnSAPChanged();
            }
        }
        private global::System.String _SAP;
        partial void OnSAPChanging(global::System.String value);
        partial void OnSAPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CADID
        {
            get
            {
                return _CADID;
            }
            set
            {
                OnCADIDChanging(value);
                ReportPropertyChanging("CADID");
                _CADID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CADID");
                OnCADIDChanged();
            }
        }
        private Nullable<global::System.Int32> _CADID;
        partial void OnCADIDChanging(Nullable<global::System.Int32> value);
        partial void OnCADIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> JobTitleID
        {
            get
            {
                return _JobTitleID;
            }
            set
            {
                OnJobTitleIDChanging(value);
                ReportPropertyChanging("JobTitleID");
                _JobTitleID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("JobTitleID");
                OnJobTitleIDChanged();
            }
        }
        private Nullable<global::System.Int32> _JobTitleID;
        partial void OnJobTitleIDChanging(Nullable<global::System.Int32> value);
        partial void OnJobTitleIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ClassificationID
        {
            get
            {
                return _ClassificationID;
            }
            set
            {
                OnClassificationIDChanging(value);
                ReportPropertyChanging("ClassificationID");
                _ClassificationID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClassificationID");
                OnClassificationIDChanged();
            }
        }
        private Nullable<global::System.Int32> _ClassificationID;
        partial void OnClassificationIDChanging(Nullable<global::System.Int32> value);
        partial void OnClassificationIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Badge
        {
            get
            {
                return _Badge;
            }
            set
            {
                OnBadgeChanging(value);
                ReportPropertyChanging("Badge");
                _Badge = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Badge");
                OnBadgeChanged();
            }
        }
        private global::System.String _Badge;
        partial void OnBadgeChanging(global::System.String value);
        partial void OnBadgeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DOB
        {
            get
            {
                return _DOB;
            }
            set
            {
                OnDOBChanging(value);
                ReportPropertyChanging("DOB");
                _DOB = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DOB");
                OnDOBChanged();
            }
        }
        private Nullable<global::System.DateTime> _DOB;
        partial void OnDOBChanging(Nullable<global::System.DateTime> value);
        partial void OnDOBChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Gender
        {
            get
            {
                return _Gender;
            }
            set
            {
                OnGenderChanging(value);
                ReportPropertyChanging("Gender");
                _Gender = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Gender");
                OnGenderChanged();
            }
        }
        private global::System.String _Gender;
        partial void OnGenderChanging(global::System.String value);
        partial void OnGenderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ethnicty
        {
            get
            {
                return _Ethnicty;
            }
            set
            {
                OnEthnictyChanging(value);
                ReportPropertyChanging("Ethnicty");
                _Ethnicty = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ethnicty");
                OnEthnictyChanged();
            }
        }
        private global::System.String _Ethnicty;
        partial void OnEthnictyChanging(global::System.String value);
        partial void OnEthnictyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MaritalStatus
        {
            get
            {
                return _MaritalStatus;
            }
            set
            {
                OnMaritalStatusChanging(value);
                ReportPropertyChanging("MaritalStatus");
                _MaritalStatus = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MaritalStatus");
                OnMaritalStatusChanged();
            }
        }
        private global::System.String _MaritalStatus;
        partial void OnMaritalStatusChanging(global::System.String value);
        partial void OnMaritalStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> HireDate
        {
            get
            {
                return _HireDate;
            }
            set
            {
                OnHireDateChanging(value);
                ReportPropertyChanging("HireDate");
                _HireDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HireDate");
                OnHireDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _HireDate;
        partial void OnHireDateChanging(Nullable<global::System.DateTime> value);
        partial void OnHireDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> rowguid
        {
            get
            {
                return _rowguid;
            }
            set
            {
                OnrowguidChanging(value);
                ReportPropertyChanging("rowguid");
                _rowguid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("rowguid");
                OnrowguidChanged();
            }
        }
        private Nullable<global::System.Guid> _rowguid;
        partial void OnrowguidChanging(Nullable<global::System.Guid> value);
        partial void OnrowguidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> WorksheetVisibleFlag
        {
            get
            {
                return _WorksheetVisibleFlag;
            }
            set
            {
                OnWorksheetVisibleFlagChanging(value);
                ReportPropertyChanging("WorksheetVisibleFlag");
                _WorksheetVisibleFlag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WorksheetVisibleFlag");
                OnWorksheetVisibleFlagChanged();
            }
        }
        private Nullable<global::System.Boolean> _WorksheetVisibleFlag;
        partial void OnWorksheetVisibleFlagChanging(Nullable<global::System.Boolean> value);
        partial void OnWorksheetVisibleFlagChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return _ModifiedDate;
            }
            set
            {
                OnModifiedDateChanging(value);
                ReportPropertyChanging("ModifiedDate");
                _ModifiedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedDate");
                OnModifiedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModifiedDate;
        partial void OnModifiedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnModifiedDateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("IECAModel", "FK_User_User_Person_Person", "Officer")]
        public Officer Person_Person
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Officer>("IECAModel.FK_User_User_Person_Person", "Officer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Officer>("IECAModel.FK_User_User_Person_Person", "Officer").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Officer> Person_PersonReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Officer>("IECAModel.FK_User_User_Person_Person", "Officer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Officer>("IECAModel.FK_User_User_Person_Person", "Officer", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
