//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("SAPDActivityModel", "FK_IECA_AuditOffice_Office_Office", "Office_Office", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(IECAWeb.Models.Office_Office), "IECA_AuditOffice", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(IECAWeb.Models.IECA_AuditOffice), true)]

#endregion

namespace IECAWeb.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class OfficeEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new OfficeEntities object using the connection string found in the 'OfficeEntities' section of the application configuration file.
        /// </summary>
        public OfficeEntities() : base("name=OfficeEntities", "OfficeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new OfficeEntities object.
        /// </summary>
        public OfficeEntities(string connectionString) : base(connectionString, "OfficeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new OfficeEntities object.
        /// </summary>
        public OfficeEntities(EntityConnection connection) : base(connection, "OfficeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<IECA_AuditOffice> IECA_AuditOffice
        {
            get
            {
                if ((_IECA_AuditOffice == null))
                {
                    _IECA_AuditOffice = base.CreateObjectSet<IECA_AuditOffice>("IECA_AuditOffice");
                }
                return _IECA_AuditOffice;
            }
        }
        private ObjectSet<IECA_AuditOffice> _IECA_AuditOffice;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Office_Office> Office_Office
        {
            get
            {
                if ((_Office_Office == null))
                {
                    _Office_Office = base.CreateObjectSet<Office_Office>("Office_Office");
                }
                return _Office_Office;
            }
        }
        private ObjectSet<Office_Office> _Office_Office;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the IECA_AuditOffice EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToIECA_AuditOffice(IECA_AuditOffice iECA_AuditOffice)
        {
            base.AddObject("IECA_AuditOffice", iECA_AuditOffice);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Office_Office EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOffice_Office(Office_Office office_Office)
        {
            base.AddObject("Office_Office", office_Office);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SAPDActivityModel", Name="IECA_AuditOffice")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class IECA_AuditOffice : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new IECA_AuditOffice object.
        /// </summary>
        /// <param name="auditOfficeID">Initial value of the AuditOfficeID property.</param>
        /// <param name="visibleFlag">Initial value of the VisibleFlag property.</param>
        public static IECA_AuditOffice CreateIECA_AuditOffice(global::System.Int32 auditOfficeID, global::System.Boolean visibleFlag)
        {
            IECA_AuditOffice iECA_AuditOffice = new IECA_AuditOffice();
            iECA_AuditOffice.AuditOfficeID = auditOfficeID;
            iECA_AuditOffice.VisibleFlag = visibleFlag;
            return iECA_AuditOffice;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AuditOfficeID
        {
            get
            {
                return _AuditOfficeID;
            }
            set
            {
                if (_AuditOfficeID != value)
                {
                    OnAuditOfficeIDChanging(value);
                    ReportPropertyChanging("AuditOfficeID");
                    _AuditOfficeID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AuditOfficeID");
                    OnAuditOfficeIDChanged();
                }
            }
        }
        private global::System.Int32 _AuditOfficeID;
        partial void OnAuditOfficeIDChanging(global::System.Int32 value);
        partial void OnAuditOfficeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean VisibleFlag
        {
            get
            {
                return _VisibleFlag;
            }
            set
            {
                OnVisibleFlagChanging(value);
                ReportPropertyChanging("VisibleFlag");
                _VisibleFlag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VisibleFlag");
                OnVisibleFlagChanged();
            }
        }
        private global::System.Boolean _VisibleFlag;
        partial void OnVisibleFlagChanging(global::System.Boolean value);
        partial void OnVisibleFlagChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SAPDActivityModel", "FK_IECA_AuditOffice_Office_Office", "Office_Office")]
        public Office_Office Office_Office
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Office_Office>("SAPDActivityModel.FK_IECA_AuditOffice_Office_Office", "Office_Office").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Office_Office>("SAPDActivityModel.FK_IECA_AuditOffice_Office_Office", "Office_Office").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Office_Office> Office_OfficeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Office_Office>("SAPDActivityModel.FK_IECA_AuditOffice_Office_Office", "Office_Office");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Office_Office>("SAPDActivityModel.FK_IECA_AuditOffice_Office_Office", "Office_Office", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SAPDActivityModel", Name="Office_Office")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Office_Office : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Office_Office object.
        /// </summary>
        /// <param name="officeID">Initial value of the OfficeID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="code">Initial value of the Code property.</param>
        public static Office_Office CreateOffice_Office(global::System.Int32 officeID, global::System.String name, global::System.String code)
        {
            Office_Office office_Office = new Office_Office();
            office_Office.OfficeID = officeID;
            office_Office.Name = name;
            office_Office.Code = code;
            return office_Office;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OfficeID
        {
            get
            {
                return _OfficeID;
            }
            set
            {
                if (_OfficeID != value)
                {
                    OnOfficeIDChanging(value);
                    ReportPropertyChanging("OfficeID");
                    _OfficeID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OfficeID");
                    OnOfficeIDChanged();
                }
            }
        }
        private global::System.Int32 _OfficeID;
        partial void OnOfficeIDChanging(global::System.Int32 value);
        partial void OnOfficeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DivisionSectionID
        {
            get
            {
                return _DivisionSectionID;
            }
            set
            {
                OnDivisionSectionIDChanging(value);
                ReportPropertyChanging("DivisionSectionID");
                _DivisionSectionID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DivisionSectionID");
                OnDivisionSectionIDChanged();
            }
        }
        private Nullable<global::System.Int32> _DivisionSectionID;
        partial void OnDivisionSectionIDChanging(Nullable<global::System.Int32> value);
        partial void OnDivisionSectionIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                OnCodeChanging(value);
                ReportPropertyChanging("Code");
                _Code = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Code");
                OnCodeChanged();
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Ranking
        {
            get
            {
                return _Ranking;
            }
            set
            {
                OnRankingChanging(value);
                ReportPropertyChanging("Ranking");
                _Ranking = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ranking");
                OnRankingChanged();
            }
        }
        private Nullable<global::System.Int32> _Ranking;
        partial void OnRankingChanging(Nullable<global::System.Int32> value);
        partial void OnRankingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Visible
        {
            get
            {
                return _Visible;
            }
            set
            {
                OnVisibleChanging(value);
                ReportPropertyChanging("Visible");
                _Visible = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Visible");
                OnVisibleChanged();
            }
        }
        private Nullable<global::System.Boolean> _Visible;
        partial void OnVisibleChanging(Nullable<global::System.Boolean> value);
        partial void OnVisibleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return _ModifiedDate;
            }
            set
            {
                OnModifiedDateChanging(value);
                ReportPropertyChanging("ModifiedDate");
                _ModifiedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedDate");
                OnModifiedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModifiedDate;
        partial void OnModifiedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnModifiedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PAOfficeID
        {
            get
            {
                return _PAOfficeID;
            }
            set
            {
                OnPAOfficeIDChanging(value);
                ReportPropertyChanging("PAOfficeID");
                _PAOfficeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PAOfficeID");
                OnPAOfficeIDChanged();
            }
        }
        private Nullable<global::System.Int32> _PAOfficeID;
        partial void OnPAOfficeIDChanging(Nullable<global::System.Int32> value);
        partial void OnPAOfficeIDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SAPDActivityModel", "FK_IECA_AuditOffice_Office_Office", "IECA_AuditOffice")]
        public IECA_AuditOffice IECA_AuditOffice
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<IECA_AuditOffice>("SAPDActivityModel.FK_IECA_AuditOffice_Office_Office", "IECA_AuditOffice").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<IECA_AuditOffice>("SAPDActivityModel.FK_IECA_AuditOffice_Office_Office", "IECA_AuditOffice").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<IECA_AuditOffice> IECA_AuditOfficeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<IECA_AuditOffice>("SAPDActivityModel.FK_IECA_AuditOffice_Office_Office", "IECA_AuditOffice");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<IECA_AuditOffice>("SAPDActivityModel.FK_IECA_AuditOffice_Office_Office", "IECA_AuditOffice", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
