//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace UserBusinessLayer
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class UserLayerEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new UserLayerEntities object using the connection string found in the 'UserLayerEntities' section of the application configuration file.
        /// </summary>
        public UserLayerEntities() : base("name=UserLayerEntities", "UserLayerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new UserLayerEntities object.
        /// </summary>
        public UserLayerEntities(string connectionString) : base(connectionString, "UserLayerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new UserLayerEntities object.
        /// </summary>
        public UserLayerEntities(EntityConnection connection) : base(connection, "UserLayerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vWebUserInfo> vWebUserInfoes
        {
            get
            {
                if ((_vWebUserInfoes == null))
                {
                    _vWebUserInfoes = base.CreateObjectSet<vWebUserInfo>("vWebUserInfoes");
                }
                return _vWebUserInfoes;
            }
        }
        private ObjectSet<vWebUserInfo> _vWebUserInfoes;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the vWebUserInfoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovWebUserInfoes(vWebUserInfo vWebUserInfo)
        {
            base.AddObject("vWebUserInfoes", vWebUserInfo);
        }

        #endregion

        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="pin">No Metadata Documentation available.</param>
        /// <param name="webSiteID">No Metadata Documentation available.</param>
        public ObjectResult<spWebSiteUserInfo_Result> spWebSiteUserInfo(global::System.String pin, Nullable<global::System.Int32> webSiteID)
        {
            ObjectParameter pinParameter;
            if (pin != null)
            {
                pinParameter = new ObjectParameter("Pin", pin);
            }
            else
            {
                pinParameter = new ObjectParameter("Pin", typeof(global::System.String));
            }
    
            ObjectParameter webSiteIDParameter;
            if (webSiteID.HasValue)
            {
                webSiteIDParameter = new ObjectParameter("WebSiteID", webSiteID);
            }
            else
            {
                webSiteIDParameter = new ObjectParameter("WebSiteID", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<spWebSiteUserInfo_Result>("spWebSiteUserInfo", pinParameter, webSiteIDParameter);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="UserModel", Name="vWebUserInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vWebUserInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vWebUserInfo object.
        /// </summary>
        /// <param name="appEntityID">Initial value of the AppEntityID property.</param>
        /// <param name="officeCode">Initial value of the OfficeCode property.</param>
        /// <param name="officeID">Initial value of the OfficeID property.</param>
        public static vWebUserInfo CreatevWebUserInfo(global::System.Int32 appEntityID, global::System.String officeCode, global::System.Int32 officeID)
        {
            vWebUserInfo vWebUserInfo = new vWebUserInfo();
            vWebUserInfo.AppEntityID = appEntityID;
            vWebUserInfo.OfficeCode = officeCode;
            vWebUserInfo.OfficeID = officeID;
            return vWebUserInfo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AppEntityID
        {
            get
            {
                return _AppEntityID;
            }
            set
            {
                if (_AppEntityID != value)
                {
                    OnAppEntityIDChanging(value);
                    ReportPropertyChanging("AppEntityID");
                    _AppEntityID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AppEntityID");
                    OnAppEntityIDChanged();
                }
            }
        }
        private global::System.Int32 _AppEntityID;
        partial void OnAppEntityIDChanging(global::System.Int32 value);
        partial void OnAppEntityIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PIN
        {
            get
            {
                return _PIN;
            }
            set
            {
                OnPINChanging(value);
                ReportPropertyChanging("PIN");
                _PIN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PIN");
                OnPINChanged();
            }
        }
        private global::System.String _PIN;
        partial void OnPINChanging(global::System.String value);
        partial void OnPINChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SAP
        {
            get
            {
                return _SAP;
            }
            set
            {
                OnSAPChanging(value);
                ReportPropertyChanging("SAP");
                _SAP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SAP");
                OnSAPChanged();
            }
        }
        private global::System.String _SAP;
        partial void OnSAPChanging(global::System.String value);
        partial void OnSAPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DutyStatus
        {
            get
            {
                return _DutyStatus;
            }
            set
            {
                OnDutyStatusChanging(value);
                ReportPropertyChanging("DutyStatus");
                _DutyStatus = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DutyStatus");
                OnDutyStatusChanged();
            }
        }
        private global::System.String _DutyStatus;
        partial void OnDutyStatusChanging(global::System.String value);
        partial void OnDutyStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OfficeCode
        {
            get
            {
                return _OfficeCode;
            }
            set
            {
                if (_OfficeCode != value)
                {
                    OnOfficeCodeChanging(value);
                    ReportPropertyChanging("OfficeCode");
                    _OfficeCode = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("OfficeCode");
                    OnOfficeCodeChanged();
                }
            }
        }
        private global::System.String _OfficeCode;
        partial void OnOfficeCodeChanging(global::System.String value);
        partial void OnOfficeCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OfficeID
        {
            get
            {
                return _OfficeID;
            }
            set
            {
                if (_OfficeID != value)
                {
                    OnOfficeIDChanging(value);
                    ReportPropertyChanging("OfficeID");
                    _OfficeID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OfficeID");
                    OnOfficeIDChanged();
                }
            }
        }
        private global::System.Int32 _OfficeID;
        partial void OnOfficeIDChanging(global::System.Int32 value);
        partial void OnOfficeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Badge
        {
            get
            {
                return _Badge;
            }
            set
            {
                OnBadgeChanging(value);
                ReportPropertyChanging("Badge");
                _Badge = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Badge");
                OnBadgeChanged();
            }
        }
        private global::System.String _Badge;
        partial void OnBadgeChanging(global::System.String value);
        partial void OnBadgeChanged();

        #endregion

    
    }

    #endregion

    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="UserModel", Name="spWebSiteUserInfo_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class spWebSiteUserInfo_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new spWebSiteUserInfo_Result object.
        /// </summary>
        /// <param name="appEntityID">Initial value of the AppEntityID property.</param>
        /// <param name="webRole">Initial value of the WebRole property.</param>
        /// <param name="officeID">Initial value of the OfficeID property.</param>
        /// <param name="officeCode">Initial value of the OfficeCode property.</param>
        public static spWebSiteUserInfo_Result CreatespWebSiteUserInfo_Result(global::System.Int32 appEntityID, global::System.String webRole, global::System.Int32 officeID, global::System.String officeCode)
        {
            spWebSiteUserInfo_Result spWebSiteUserInfo_Result = new spWebSiteUserInfo_Result();
            spWebSiteUserInfo_Result.AppEntityID = appEntityID;
            spWebSiteUserInfo_Result.WebRole = webRole;
            spWebSiteUserInfo_Result.OfficeID = officeID;
            spWebSiteUserInfo_Result.OfficeCode = officeCode;
            return spWebSiteUserInfo_Result;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AppEntityID
        {
            get
            {
                return _AppEntityID;
            }
            set
            {
                OnAppEntityIDChanging(value);
                ReportPropertyChanging("AppEntityID");
                _AppEntityID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AppEntityID");
                OnAppEntityIDChanged();
            }
        }
        private global::System.Int32 _AppEntityID;
        partial void OnAppEntityIDChanging(global::System.Int32 value);
        partial void OnAppEntityIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PIN
        {
            get
            {
                return _PIN;
            }
            set
            {
                OnPINChanging(value);
                ReportPropertyChanging("PIN");
                _PIN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PIN");
                OnPINChanged();
            }
        }
        private global::System.String _PIN;
        partial void OnPINChanging(global::System.String value);
        partial void OnPINChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String WebRole
        {
            get
            {
                return _WebRole;
            }
            set
            {
                OnWebRoleChanging(value);
                ReportPropertyChanging("WebRole");
                _WebRole = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("WebRole");
                OnWebRoleChanged();
            }
        }
        private global::System.String _WebRole;
        partial void OnWebRoleChanging(global::System.String value);
        partial void OnWebRoleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OfficeID
        {
            get
            {
                return _OfficeID;
            }
            set
            {
                OnOfficeIDChanging(value);
                ReportPropertyChanging("OfficeID");
                _OfficeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OfficeID");
                OnOfficeIDChanged();
            }
        }
        private global::System.Int32 _OfficeID;
        partial void OnOfficeIDChanging(global::System.Int32 value);
        partial void OnOfficeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OfficeCode
        {
            get
            {
                return _OfficeCode;
            }
            set
            {
                OnOfficeCodeChanging(value);
                ReportPropertyChanging("OfficeCode");
                _OfficeCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OfficeCode");
                OnOfficeCodeChanged();
            }
        }
        private global::System.String _OfficeCode;
        partial void OnOfficeCodeChanging(global::System.String value);
        partial void OnOfficeCodeChanged();

        #endregion

    }

    #endregion

    
}
