//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("SAPDActivityModel", "FK_Award_Recognize_Award_AwardType", "Award_AwardType", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(RecognitionBusinessLayer.AwardType), "Award_Recognize", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RecognitionBusinessLayer.Recognize), true)]
[assembly: EdmRelationshipAttribute("SAPDActivityModel", "FK_Award_Recognize_Award_RecognitionType", "Award_RecognitionType", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(RecognitionBusinessLayer.RecognitionType), "Award_Recognize", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RecognitionBusinessLayer.Recognize), true)]
[assembly: EdmRelationshipAttribute("SAPDActivityModel", "PersonRecognize", "Person", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(RecognitionBusinessLayer.Person), "Recognize", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RecognitionBusinessLayer.Recognize), true)]
[assembly: EdmRelationshipAttribute("SAPDActivityModel", "FK_Award_Recognize_Office_Office", "Office_Office", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(RecognitionBusinessLayer.Office_Office), "Recognize", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RecognitionBusinessLayer.Recognize), true)]

#endregion

namespace RecognitionBusinessLayer
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SAPDActivityEntities1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SAPDActivityEntities1 object using the connection string found in the 'SAPDActivityEntities1' section of the application configuration file.
        /// </summary>
        public SAPDActivityEntities1() : base("name=SAPDActivityEntities1", "SAPDActivityEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SAPDActivityEntities1 object.
        /// </summary>
        public SAPDActivityEntities1(string connectionString) : base(connectionString, "SAPDActivityEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SAPDActivityEntities1 object.
        /// </summary>
        public SAPDActivityEntities1(EntityConnection connection) : base(connection, "SAPDActivityEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AwardType> AwardTypes
        {
            get
            {
                if ((_AwardTypes == null))
                {
                    _AwardTypes = base.CreateObjectSet<AwardType>("AwardTypes");
                }
                return _AwardTypes;
            }
        }
        private ObjectSet<AwardType> _AwardTypes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RecognitionType> RecognitionTypes
        {
            get
            {
                if ((_RecognitionTypes == null))
                {
                    _RecognitionTypes = base.CreateObjectSet<RecognitionType>("RecognitionTypes");
                }
                return _RecognitionTypes;
            }
        }
        private ObjectSet<RecognitionType> _RecognitionTypes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Recognize> Recognizes
        {
            get
            {
                if ((_Recognizes == null))
                {
                    _Recognizes = base.CreateObjectSet<Recognize>("Recognizes");
                }
                return _Recognizes;
            }
        }
        private ObjectSet<Recognize> _Recognizes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Person> People
        {
            get
            {
                if ((_People == null))
                {
                    _People = base.CreateObjectSet<Person>("People");
                }
                return _People;
            }
        }
        private ObjectSet<Person> _People;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Office_Office> Office_Office
        {
            get
            {
                if ((_Office_Office == null))
                {
                    _Office_Office = base.CreateObjectSet<Office_Office>("Office_Office");
                }
                return _Office_Office;
            }
        }
        private ObjectSet<Office_Office> _Office_Office;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AwardTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAwardTypes(AwardType awardType)
        {
            base.AddObject("AwardTypes", awardType);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RecognitionTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRecognitionTypes(RecognitionType recognitionType)
        {
            base.AddObject("RecognitionTypes", recognitionType);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Recognizes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRecognizes(Recognize recognize)
        {
            base.AddObject("Recognizes", recognize);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the People EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPeople(Person person)
        {
            base.AddObject("People", person);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Office_Office EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOffice_Office(Office_Office office_Office)
        {
            base.AddObject("Office_Office", office_Office);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SAPDActivityModel", Name="AwardType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AwardType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AwardType object.
        /// </summary>
        /// <param name="awardTypeId">Initial value of the AwardTypeId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static AwardType CreateAwardType(global::System.Int32 awardTypeId, global::System.String name)
        {
            AwardType awardType = new AwardType();
            awardType.AwardTypeId = awardTypeId;
            awardType.Name = name;
            return awardType;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AwardTypeId
        {
            get
            {
                return _AwardTypeId;
            }
            set
            {
                if (_AwardTypeId != value)
                {
                    OnAwardTypeIdChanging(value);
                    ReportPropertyChanging("AwardTypeId");
                    _AwardTypeId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AwardTypeId");
                    OnAwardTypeIdChanged();
                }
            }
        }
        private global::System.Int32 _AwardTypeId;
        partial void OnAwardTypeIdChanging(global::System.Int32 value);
        partial void OnAwardTypeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                OnCodeChanging(value);
                ReportPropertyChanging("Code");
                _Code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Code");
                OnCodeChanged();
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SAPDActivityModel", "FK_Award_Recognize_Award_AwardType", "Award_Recognize")]
        public EntityCollection<Recognize> Award_Recognize
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Recognize>("SAPDActivityModel.FK_Award_Recognize_Award_AwardType", "Award_Recognize");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Recognize>("SAPDActivityModel.FK_Award_Recognize_Award_AwardType", "Award_Recognize", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SAPDActivityModel", Name="Office_Office")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Office_Office : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Office_Office object.
        /// </summary>
        /// <param name="officeID">Initial value of the OfficeID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="code">Initial value of the Code property.</param>
        public static Office_Office CreateOffice_Office(global::System.Int32 officeID, global::System.String name, global::System.String code)
        {
            Office_Office office_Office = new Office_Office();
            office_Office.OfficeID = officeID;
            office_Office.Name = name;
            office_Office.Code = code;
            return office_Office;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OfficeID
        {
            get
            {
                return _OfficeID;
            }
            set
            {
                if (_OfficeID != value)
                {
                    OnOfficeIDChanging(value);
                    ReportPropertyChanging("OfficeID");
                    _OfficeID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OfficeID");
                    OnOfficeIDChanged();
                }
            }
        }
        private global::System.Int32 _OfficeID;
        partial void OnOfficeIDChanging(global::System.Int32 value);
        partial void OnOfficeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DivisionSectionID
        {
            get
            {
                return _DivisionSectionID;
            }
            set
            {
                OnDivisionSectionIDChanging(value);
                ReportPropertyChanging("DivisionSectionID");
                _DivisionSectionID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DivisionSectionID");
                OnDivisionSectionIDChanged();
            }
        }
        private Nullable<global::System.Int32> _DivisionSectionID;
        partial void OnDivisionSectionIDChanging(Nullable<global::System.Int32> value);
        partial void OnDivisionSectionIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                OnCodeChanging(value);
                ReportPropertyChanging("Code");
                _Code = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Code");
                OnCodeChanged();
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Ranking
        {
            get
            {
                return _Ranking;
            }
            set
            {
                OnRankingChanging(value);
                ReportPropertyChanging("Ranking");
                _Ranking = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ranking");
                OnRankingChanged();
            }
        }
        private Nullable<global::System.Int32> _Ranking;
        partial void OnRankingChanging(Nullable<global::System.Int32> value);
        partial void OnRankingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Visible
        {
            get
            {
                return _Visible;
            }
            set
            {
                OnVisibleChanging(value);
                ReportPropertyChanging("Visible");
                _Visible = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Visible");
                OnVisibleChanged();
            }
        }
        private Nullable<global::System.Boolean> _Visible;
        partial void OnVisibleChanging(Nullable<global::System.Boolean> value);
        partial void OnVisibleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return _ModifiedDate;
            }
            set
            {
                OnModifiedDateChanging(value);
                ReportPropertyChanging("ModifiedDate");
                _ModifiedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedDate");
                OnModifiedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModifiedDate;
        partial void OnModifiedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnModifiedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PAOfficeID
        {
            get
            {
                return _PAOfficeID;
            }
            set
            {
                OnPAOfficeIDChanging(value);
                ReportPropertyChanging("PAOfficeID");
                _PAOfficeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PAOfficeID");
                OnPAOfficeIDChanged();
            }
        }
        private Nullable<global::System.Int32> _PAOfficeID;
        partial void OnPAOfficeIDChanging(Nullable<global::System.Int32> value);
        partial void OnPAOfficeIDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SAPDActivityModel", "FK_Award_Recognize_Office_Office", "Recognize")]
        public EntityCollection<Recognize> Award_Recognize
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Recognize>("SAPDActivityModel.FK_Award_Recognize_Office_Office", "Recognize");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Recognize>("SAPDActivityModel.FK_Award_Recognize_Office_Office", "Recognize", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SAPDActivityModel", Name="Person")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Person : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Person object.
        /// </summary>
        /// <param name="appEntityID">Initial value of the AppEntityID property.</param>
        public static Person CreatePerson(global::System.Int32 appEntityID)
        {
            Person person = new Person();
            person.AppEntityID = appEntityID;
            return person;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AppEntityID
        {
            get
            {
                return _AppEntityID;
            }
            set
            {
                if (_AppEntityID != value)
                {
                    OnAppEntityIDChanging(value);
                    ReportPropertyChanging("AppEntityID");
                    _AppEntityID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AppEntityID");
                    OnAppEntityIDChanged();
                }
            }
        }
        private global::System.Int32 _AppEntityID;
        partial void OnAppEntityIDChanging(global::System.Int32 value);
        partial void OnAppEntityIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PersonTypeID
        {
            get
            {
                return _PersonTypeID;
            }
            set
            {
                OnPersonTypeIDChanging(value);
                ReportPropertyChanging("PersonTypeID");
                _PersonTypeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PersonTypeID");
                OnPersonTypeIDChanged();
            }
        }
        private Nullable<global::System.Int32> _PersonTypeID;
        partial void OnPersonTypeIDChanging(Nullable<global::System.Int32> value);
        partial void OnPersonTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MiddleName
        {
            get
            {
                return _MiddleName;
            }
            set
            {
                OnMiddleNameChanging(value);
                ReportPropertyChanging("MiddleName");
                _MiddleName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MiddleName");
                OnMiddleNameChanged();
            }
        }
        private global::System.String _MiddleName;
        partial void OnMiddleNameChanging(global::System.String value);
        partial void OnMiddleNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Suffix
        {
            get
            {
                return _Suffix;
            }
            set
            {
                OnSuffixChanging(value);
                ReportPropertyChanging("Suffix");
                _Suffix = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Suffix");
                OnSuffixChanged();
            }
        }
        private global::System.String _Suffix;
        partial void OnSuffixChanging(global::System.String value);
        partial void OnSuffixChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> rowguid
        {
            get
            {
                return _rowguid;
            }
            set
            {
                OnrowguidChanging(value);
                ReportPropertyChanging("rowguid");
                _rowguid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("rowguid");
                OnrowguidChanged();
            }
        }
        private Nullable<global::System.Guid> _rowguid;
        partial void OnrowguidChanging(Nullable<global::System.Guid> value);
        partial void OnrowguidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return _ModifiedDate;
            }
            set
            {
                OnModifiedDateChanging(value);
                ReportPropertyChanging("ModifiedDate");
                _ModifiedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedDate");
                OnModifiedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModifiedDate;
        partial void OnModifiedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnModifiedDateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SAPDActivityModel", "PersonRecognize", "Recognize")]
        public EntityCollection<Recognize> Recognizes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Recognize>("SAPDActivityModel.PersonRecognize", "Recognize");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Recognize>("SAPDActivityModel.PersonRecognize", "Recognize", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SAPDActivityModel", Name="RecognitionType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RecognitionType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RecognitionType object.
        /// </summary>
        /// <param name="recognitionTypeId">Initial value of the RecognitionTypeId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static RecognitionType CreateRecognitionType(global::System.Int32 recognitionTypeId, global::System.String name)
        {
            RecognitionType recognitionType = new RecognitionType();
            recognitionType.RecognitionTypeId = recognitionTypeId;
            recognitionType.Name = name;
            return recognitionType;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RecognitionTypeId
        {
            get
            {
                return _RecognitionTypeId;
            }
            set
            {
                if (_RecognitionTypeId != value)
                {
                    OnRecognitionTypeIdChanging(value);
                    ReportPropertyChanging("RecognitionTypeId");
                    _RecognitionTypeId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RecognitionTypeId");
                    OnRecognitionTypeIdChanged();
                }
            }
        }
        private global::System.Int32 _RecognitionTypeId;
        partial void OnRecognitionTypeIdChanging(global::System.Int32 value);
        partial void OnRecognitionTypeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                OnCodeChanging(value);
                ReportPropertyChanging("Code");
                _Code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Code");
                OnCodeChanged();
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SAPDActivityModel", "FK_Award_Recognize_Award_RecognitionType", "Award_Recognize")]
        public EntityCollection<Recognize> Award_Recognize
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Recognize>("SAPDActivityModel.FK_Award_Recognize_Award_RecognitionType", "Award_Recognize");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Recognize>("SAPDActivityModel.FK_Award_Recognize_Award_RecognitionType", "Award_Recognize", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SAPDActivityModel", Name="Recognize")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Recognize : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Recognize object.
        /// </summary>
        /// <param name="recognitionId">Initial value of the RecognitionId property.</param>
        /// <param name="recogTypeId">Initial value of the RecogTypeId property.</param>
        /// <param name="appEntityID">Initial value of the AppEntityID property.</param>
        /// <param name="officeId">Initial value of the OfficeId property.</param>
        /// <param name="issuedDate">Initial value of the IssuedDate property.</param>
        public static Recognize CreateRecognize(global::System.Int32 recognitionId, global::System.Int32 recogTypeId, global::System.Int32 appEntityID, global::System.Int32 officeId, global::System.DateTime issuedDate)
        {
            Recognize recognize = new Recognize();
            recognize.RecognitionId = recognitionId;
            recognize.RecogTypeId = recogTypeId;
            recognize.AppEntityID = appEntityID;
            recognize.OfficeId = officeId;
            recognize.IssuedDate = issuedDate;
            return recognize;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RecognitionId
        {
            get
            {
                return _RecognitionId;
            }
            set
            {
                if (_RecognitionId != value)
                {
                    OnRecognitionIdChanging(value);
                    ReportPropertyChanging("RecognitionId");
                    _RecognitionId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RecognitionId");
                    OnRecognitionIdChanged();
                }
            }
        }
        private global::System.Int32 _RecognitionId;
        partial void OnRecognitionIdChanging(global::System.Int32 value);
        partial void OnRecognitionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RecogTypeId
        {
            get
            {
                return _RecogTypeId;
            }
            set
            {
                OnRecogTypeIdChanging(value);
                ReportPropertyChanging("RecogTypeId");
                _RecogTypeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RecogTypeId");
                OnRecogTypeIdChanged();
            }
        }
        private global::System.Int32 _RecogTypeId;
        partial void OnRecogTypeIdChanging(global::System.Int32 value);
        partial void OnRecogTypeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AwardTypeId
        {
            get
            {
                return _AwardTypeId;
            }
            set
            {
                OnAwardTypeIdChanging(value);
                ReportPropertyChanging("AwardTypeId");
                _AwardTypeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AwardTypeId");
                OnAwardTypeIdChanged();
            }
        }
        private Nullable<global::System.Int32> _AwardTypeId;
        partial void OnAwardTypeIdChanging(Nullable<global::System.Int32> value);
        partial void OnAwardTypeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AppEntityID
        {
            get
            {
                return _AppEntityID;
            }
            set
            {
                OnAppEntityIDChanging(value);
                ReportPropertyChanging("AppEntityID");
                _AppEntityID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AppEntityID");
                OnAppEntityIDChanged();
            }
        }
        private global::System.Int32 _AppEntityID;
        partial void OnAppEntityIDChanging(global::System.Int32 value);
        partial void OnAppEntityIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OfficeId
        {
            get
            {
                return _OfficeId;
            }
            set
            {
                OnOfficeIdChanging(value);
                ReportPropertyChanging("OfficeId");
                _OfficeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OfficeId");
                OnOfficeIdChanged();
            }
        }
        private global::System.Int32 _OfficeId;
        partial void OnOfficeIdChanging(global::System.Int32 value);
        partial void OnOfficeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Notes
        {
            get
            {
                return _Notes;
            }
            set
            {
                OnNotesChanging(value);
                ReportPropertyChanging("Notes");
                _Notes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Notes");
                OnNotesChanged();
            }
        }
        private global::System.String _Notes;
        partial void OnNotesChanging(global::System.String value);
        partial void OnNotesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DocPath
        {
            get
            {
                return _DocPath;
            }
            set
            {
                OnDocPathChanging(value);
                ReportPropertyChanging("DocPath");
                _DocPath = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DocPath");
                OnDocPathChanged();
            }
        }
        private global::System.String _DocPath;
        partial void OnDocPathChanging(global::System.String value);
        partial void OnDocPathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime IssuedDate
        {
            get
            {
                return _IssuedDate;
            }
            set
            {
                OnIssuedDateChanging(value);
                ReportPropertyChanging("IssuedDate");
                _IssuedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IssuedDate");
                OnIssuedDateChanged();
            }
        }
        private global::System.DateTime _IssuedDate;
        partial void OnIssuedDateChanging(global::System.DateTime value);
        partial void OnIssuedDateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SAPDActivityModel", "FK_Award_Recognize_Award_AwardType", "Award_AwardType")]
        public AwardType Award_AwardType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AwardType>("SAPDActivityModel.FK_Award_Recognize_Award_AwardType", "Award_AwardType").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AwardType>("SAPDActivityModel.FK_Award_Recognize_Award_AwardType", "Award_AwardType").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<AwardType> Award_AwardTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AwardType>("SAPDActivityModel.FK_Award_Recognize_Award_AwardType", "Award_AwardType");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<AwardType>("SAPDActivityModel.FK_Award_Recognize_Award_AwardType", "Award_AwardType", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SAPDActivityModel", "FK_Award_Recognize_Award_RecognitionType", "Award_RecognitionType")]
        public RecognitionType Award_RecognitionType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RecognitionType>("SAPDActivityModel.FK_Award_Recognize_Award_RecognitionType", "Award_RecognitionType").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RecognitionType>("SAPDActivityModel.FK_Award_Recognize_Award_RecognitionType", "Award_RecognitionType").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<RecognitionType> Award_RecognitionTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RecognitionType>("SAPDActivityModel.FK_Award_Recognize_Award_RecognitionType", "Award_RecognitionType");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<RecognitionType>("SAPDActivityModel.FK_Award_Recognize_Award_RecognitionType", "Award_RecognitionType", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SAPDActivityModel", "PersonRecognize", "Person")]
        public Person Person
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Person>("SAPDActivityModel.PersonRecognize", "Person").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Person>("SAPDActivityModel.PersonRecognize", "Person").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Person> PersonReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Person>("SAPDActivityModel.PersonRecognize", "Person");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Person>("SAPDActivityModel.PersonRecognize", "Person", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SAPDActivityModel", "FK_Award_Recognize_Office_Office", "Office_Office")]
        public Office_Office Office_Office
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Office_Office>("SAPDActivityModel.FK_Award_Recognize_Office_Office", "Office_Office").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Office_Office>("SAPDActivityModel.FK_Award_Recognize_Office_Office", "Office_Office").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Office_Office> Office_OfficeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Office_Office>("SAPDActivityModel.FK_Award_Recognize_Office_Office", "Office_Office");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Office_Office>("SAPDActivityModel.FK_Award_Recognize_Office_Office", "Office_Office", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
